### ISSUE TITLE
Support for multiple delimiter OR detect of delimiter

### ISSUE THREAD

**Issue by kamikat** [adaltas/node-csv#126]
I have a problem that some application generate CSV with dialect different from MS Excel one (use `\t` as delimiter) and I can't limit my user to use a specific CSV dialect.

So, I wonder if it's possible to add support for multiple delimiter characters.

``` javascript
csv()
.from('/path/to/file.csv', {
  delimiter: ',\t'
})
```

Or, Is there any module that can detect which CSV dialect did the file uploaded by user use?

**Comment by wdavidw** [comment]
Doing some cleanup.

**Comment by jamiter** [comment]
@wdavidw, thanks for all the great work! Do I understand correctly that auto-detecting delimiter hasn't been implemented?
