### ISSUE TITLE
Default 'comment' char of # truncates csv data rows

### ISSUE THREAD

**Issue by jsfunfun** [adaltas/node-csv#135]
Just an observation, but my data includes RGB hex color codes such as #ffcc95 which by the design of how the CSV parser operates would therefore eliminate the remainder of my data line - believing the # to be a comment (which it does :))... 

So perhaps a way to turn off the comment feature is appropriate (such as make the char comment blank '').

Then add an 'ignoreLineChar' which if this is the first char of a line then ignore the whole line itself... (which is useful for documenting headers).

Cheers - otherwise, love the product and thank you very very much for all your hard work and efforts..

**Comment by wdavidw** [comment]
Doing some cleanup.
