### ISSUE TITLE
Transform doesn't work from within a child_process

### ISSUE THREAD

**Issue by dmgreene** [adaltas/node-csv#138]
- Issue:  
  My node process creates a large csv via your product and since node is single-threaded, all of the users are locked up during the 4 minutes or so that it takes node-csv to create the file.
- Findings: 

I tried running csv() from a child_process to see if that would work, but for some reason when I do that I never get a callback from csv().transform().

After putting some logging statements into the csv code, it looks like Transformer.prototype.write() is never being hit.  Could that be part of the problem?  
- Questions:

Has anyone else tried to run node-csv as a child process?
Also, does anyone of another way to have node-csv not block other users of the website?

**Comment by wdavidw** [comment]
Doing some cleanup.
