### ISSUE TITLE
Feature request: 'preprocess' directive

### ISSUE THREAD

**Issue by giacecco** [adaltas/node-csv#152]
Dear wdavidw,
It often happens to me that I need to process badly formatted CSV files that include, for example, unescaped double quotes. Of course I could fix that outside of Node, but ideally I would like to do that within node-csv, perhaps with a 'preprocess' directive, like 'transform' but that gives me access to the entire row as a string rather than an object.

```
csv()
.from.stream(whatever)
.to.stream(whatever)
    .preprocess(function (rowAsString, index) {
            return processedRowAsString;
    })
.transform(function (row, index) {
        etc. etc.
```

What do you reckon? Would that be useful?

Giacecco

**Comment by wdavidw** [comment]
Doing some cleanup.
