### ISSUE TITLE
RowDelimiter is placed in the front of the row rather than back

### ISSUE THREAD

**Issue by sidazhang** [adaltas/node-csv#157]
I find that the module will read a piece of data like below

```
'data', 'data2'\n'data3', 'data4'
```

into this format

```
'data', 'data2'
\n'data3', 'data4'
```

where the row delimiter is placed to the front of the next row, rather than the end of each row. Is there a way to reverse the behaviour?

Note:

The expected behaviour should be

```
'data', 'data2'\n
'data3', 'data4'
```

**Comment by wdavidw** [comment]
Doing some cleanup.
