### ISSUE TITLE
Changelog.md?

### ISSUE THREAD

**Issue by ilanbiala** [adaltas/node-csv#189]
Changelog.md for seeing API changes, features changes, performance changes, bug fixes, etc.

**Comment by ilanbiala** [comment]
@wdavidw is there a changelog in progress?

**Comment by wdavidw** [comment]
I must admit that I have a hard time maintaining a changelog for open source projets, they tends to be inaccurate after time. but you're right, this project is quite mature and would deserve one.

**Comment by ilanbiala** [comment]
@wdavidw if you are the only one managing this repo, then how could it be inaccurate if you update it when you publish to npm?

**Comment by wdavidw** [comment]
because i forget to do it

**Comment by ilanbiala** [comment]
Just add an `npm postpublish` script...

**Comment by wdavidw** [comment]
do u have sth in mind, like [semantic-release](https://www.npmjs.com/package/semantic-release)?

**Comment by pensierinmusica** [comment]
+1 Yey, please add a changelog  :)

**Comment by seoker** [comment]
+1
How can I know what breaks when I upgrade from 1.X to 2.0? :(

**Comment by wdavidw** [comment]
By making a contribution!
