### ISSUE TITLE
Customize decimal separator in csv-parse

### ISSUE THREAD

**Issue by bobby77** [adaltas/node-csv#199]
Hello,
The csv-parse property [parse.regexp_float] gives the regular expression used to cast a number as a float if options.auto_parse = true.

Currently, it is: /^(-|+)?([0-9]+(.[0-9]+)?([eE][0-9]+)?|Infinity)$/
-> ie: The decimal separator has to be "."

Is it possible to customize this regular expression?
I would like to be able to set the decimal separator as either "." or "," 

Would it be useful to add this customize functionality? Or is there another solution?
Currently I need to parse again all the values in order to convert strings to numbers after csv-parse has done its job.

Thanks a lot for your reply. I am not sure if it is the right place to ask for a new feature.
Regards.

**Comment by wdavidw** [comment]
Doing some cleanup.
