### ISSUE TITLE
When simple parser gets error, no finish or end event is raised leaving code to hang

### ISSUE THREAD

**Issue by ttarrant** [adaltas/node-csv#209]
simple parsing as shown in the following code outline never ends.

`var fs = require('fs');
var csv = require('csv');

var input = fs.createReadStream(timesheetHistory.path)
var parser = csv.parse({
    ...
}).on('readable', function () {
    // this gets called
}).on('error', function(err) {
    // this gets called twice in our case
    console.log('PARSER ERROR ************_');
}).on('finish', function () {
    // this never gets called
    console.log('PARSER FINISH ***_********_');
}).on('end', function(err) {
    // this never gets called
    console.log('PARSER END ***_********_');
}).on('close', function(err) {
    // this never gets called
    console.log('PARSER CLOSE ***_*********');
});
input.pipe(parser);`

// apologies for the code not begin formatted.. I couldn't get the markup to respect it

**Comment by wdavidw** [comment]
as far as i know, this respect the Node.js stream api contract, dont u agree?

**Comment by ttarrant** [comment]
I don't think so, We will put together a test case to highlight our
scenario. At the moment we are doing things like 'if called' don't re-call
the callback, but I'm concerned about what's left 'hanging around' d on the
error case

**Comment by wdavidw** [comment]
Doing some cleanup.
