### ISSUE TITLE
request: recover from "Error: Invalid closing quote at line"

### ISSUE THREAD

**Issue by jobe451** [adaltas/node-csv#214]
Sometimes I get files form customers that have improperly escaped values, like
"foo", "bar", "foo "bar""

Which then correctly results in the error
"Error: Invalid closing quote at line ..."

I have a case where this happens very seldomly (8 in 200K records are affected).

It would be much better, if the system would be able to skip the current record, write a warning and continue with the next record.

Doing this, is not 'safe' in every situation. However, if one assumes, that there is no record delimiter in any of the columns, it would be safe to search for the next EOL and continue. (Often enough, this assumption can be safely made).

The parser could be configured, to assume "no EOL in content". With this configuration, it would continue processing. The default should be to have this behaviour turned of.

This would be a behaviour that would be quite adequate for my current case. Otherwise I have to argue with a customer on wrong CSV files, which he might understand or not. Assuming they the problem, they still would need to "implement" a fix, which might take a long time. On the other side, in this case, having <1% records skipped, will not make any difference to the quality of the service.

**Comment by wdavidw** [comment]
there is no way to know when is the next record, for exemple [this test](https://github.com/wdavidw/node-csv-parse/blob/master/test/options.quote.coffee#L58-L73). a line feed (\r and \n) are perfectly valid inside a quoted value. this isnt the first time this issue is raised. maybe an option like "skip_to_next_line_on_error" would be the proper way to handle it.

**Comment by jobe451** [comment]
If you assume that there will never be a line feed (\r and \n) in a column, you actually can determine what the next record will be. You simply continue till you find \r\n-ish.

There are cases where such an assumption is quite valid. Let's say there is a list of addresses. All the addresses where entered via a UI, that does not allow linefeeds. So it is very unlikely that there will be line-feeds in the content. 

I work for a company that does process a large number of csv-data-feeds from a large number of customers. Very big ones as well as one-man-businesses. Messing up the escaping is quite common. There is a lot of developers that rather decide for an 'seldom' record delimiter like the pipe-symbol, rather then doing the escaping right. On the other hand, I hardly ever have to deal with content that has line-feeds in the actual content. I beliefe this is quite often the case in practice and not only restricted to my sepcific situation. 

So what I do suggest is to put it into the hands of the developer using the library to decide, whether he wants to rely on that assumption of no "EOL in content" and rather skip to the next record on invalid escaping.

**Comment by wdavidw** [comment]
This is what i proposed as well, let the developer decide by creating a new option that can be activated on demand. Note, I wrote line feed, but to be more correct, I should have wrote the value of the "rowDelimiter" option.

**Comment by jobe451** [comment]
Got it. Yes, "skip_to_next_line_on_error" would be an awesome feature.

**Comment by karlbecker** [comment]
Fully agreed.  This is _highly_ desired for me.

Without a "skip to next row on error", it appears to be impossible to resume where a malformed CSV file causes an error to happen.  This would also answer [this issue](https://github.com/wdavidw/node-csv-parse/issues/93) and a few others I noticed.

**Comment by jobe451** [comment]
I did patch csv-parse so that it understands the option 'skipToNextLineOnError'. I have never used coffeeScript, so I did it directly on the javascript.

At least my test cases still pass. I can process a 200K file with 7 malformed records. 

The full code can be found here:
https://jsfiddle.net/jobe451/6h8vy4td/

This is the diff:
```diff
Left file: csv-parse\lib\index - old.js
Right file: csv-parse\lib\index.js
258a259
>   var lineHasError = false;
358,359c360,367
<             throw Error("Invalid closing quote at line " + (this.lines + 1) + "; found " + (JSON.stringify(this.nextChar)) + " instead of delimiter " + (JSON.stringify(this.options.delimiter)));
---
>             if(this.options.skipToNextLineOnError) {
>               if (!lineHasError) {
>                 lineHasError = true;
>                 console.log("Invalid closing quote at line " + (this.lines + 1) + "; found " + (JSON.stringify(this.nextChar)) + " instead of delimiter " + (JSON.stringify(this.options.delimiter)));
>               }
>             } else {
>               throw Error("Invalid closing quote at line " + (this.lines + 1) + "; found " + (JSON.stringify(this.nextChar)) + " instead of delimiter " + (JSON.stringify(this.options.delimiter)));
>             }
415,416c424,429
<         this.__push(this.line);
---
>         if (lineHasError) {
>           lineHasError = false;
>         }
>         else {
>           this.__push(this.line);          
>         }
```

**Comment by karlbecker** [comment]
@jobe451 - you're a lifesaver!  Thank you! 👏 👏 👏 

This kind of approach is exactly what could work; I haven't done coffeeScript, either, but perhaps I'll give it a shot early next week to see if I can write up the test case and implement your logic.

Did you fork it and put that code in, or just have it on your local machine?  I'm going to use this from a fork (I'll make my own if needed) in my production app so I can solve a problem we're currently facing, but then would love to see this in the main branch so I can switch back to it.

**Comment by jobe451** [comment]
I just grabed the javascript from the npm installation and changed it the hacky way.

I didn't fork it, since this would have meant to get familiar with coffee script plus setting up the coffee script compiler. So I just did the fix, published it here and hoped that somebody could pick it up from there.

I would also appreciate if this could make it into the main branch. I guess it's also worth if a second person could double check the change.

**Comment by fboutin-pmc** [comment]
> in this case, having records skipped, will not make any difference to the quality of the service.

That's not true. The actual solution does NOT tell if a parsing error occurred so you think that everything is fine which is NOT. So you might skip some important data and you don't even know.

**Comment by wdavidw** [comment]
@fboutin-pmc we are currently emitting a "skip" event when the `skip_lines_with_error` option is activated and an error is found. Are you suggesting we shall provide additional information along this event or that the implementation suffer from a bug?

**Comment by fboutin-pmc** [comment]
No no. I do NOT say there is a bug. I thought the statement made by the author was fallacious.

I would kindly ask you to point me on the documentation that would teach me on how to listen on events like the skip event, please.

**Comment by wdavidw** [comment]
Well, I went straight into the code and seach for `skip`. I'll scratch a page for this option now.

**Comment by wdavidw** [comment]
Page is [online](https://csv.js.org/parse/options/skip_lines_with_error/). Please fix the typos by clicking on the top left pencil icon.

**Comment by wdavidw** [comment]
>  I get it, you have to use the Stream API...
This could also be added to the `info` argument in the form of a skip array. Dont have the time to implement it at the moment but maybe someone would enjoy making a contribution, it shouldn't be hard at all.
