### ISSUE TITLE
Multiple row delimiters

### ISSUE THREAD

**Issue by vamzz1** [adaltas/node-csv#216]
Currently itseems like we can specify only one string as the row delimiter. Is it possible to set multiple strings??

**Comment by wdavidw** [comment]
u mean something like `{rowDelimiter: ['\n', '\r']`. I dont remember implementing this, would accept a pull request if it contains a test and if u find the time for it.

**Comment by vamzz1** [comment]
Yes something like that, it's highly unlikely but i've come across a case where there are different types of row delimiters within a file.

**Comment by wdavidw** [comment]
I'm not surprised, it came to my mind before and I know that sooner or later, this day will come

**Comment by wdavidw** [comment]
Doing some cleanup.
