### ISSUE TITLE
how do I use options in TypeScript

### ISSUE THREAD

**Issue by eliprand** [adaltas/node-csv#219]
Hi,
Trying to use this awesome library as part of a TypeScript project. Though I have been doing TypeScript for a few months now, I seem to have a lot of trouble using the `options` type.
Using the type definitions from `@types/csv-parse`, I am able to successfully import and use `parse` as follows:
```
import * as parse from 'csv-parse';
```

However, to help with discovery, I want to declare an options variable as follows:
```
const options : options = {
    delimiter: ',',
    quote: '"'
};
```

**What `import` statement should I use to do that?**
When I use the following, while it compiles fine, I end up with a `Cannot find module 'csv-parse/types'` error at runtime:
```
import {options} from 'csv-parse/types';
```

If I drop that line and use `any` type for my `options`, it runs fine and compiles fine, but I obviously loose intellisense and type-checking in my code.

**Comment by wdavidw** [comment]
I'm not familiar with TypeScript but It seems quite normal you get such an error when importing a module which does not exists. I'm not against creating this types file f it help to have such a meta information file for TypeScript users.

**Comment by eliprand** [comment]
Thanks for the quick response. Looks like `andy-ms` was the one who posted those on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/csv-parse).
Sounds like I should file a bug (or submit a patch) against that project instead.

**Comment by wdavidw** [comment]
I think we shall get in touch with @andy-ms and propose him to import those information here if they apply to this package

**Comment by andy-ms** [comment]
DefinitelyTyped/DefinitelyTyped#15024 should allow you to `import { Options } from "csv-parse"` directly.

**Comment by eliprand** [comment]
@andy-ms Thanks for the update. Looks like `import { options } from 'csv-parse';` is not working. Looking at the definition file, those types are declared in `module 'csv-parse/types'` but are not re-exported.
I can't say I have a lot of experience with definition files, so don't expect anything immediate on that.

**Comment by andy-ms** [comment]
That pull request isn't merged yet so it won't work immediately.

**Comment by eliprand** [comment]
Ah, had missed that small, yet important detail. I will give it a shot.

**Comment by wdavidw** [comment]
i'm addressing this question to all TypeScript users. What would you prefer, having the type definitions along the original package (in our case csv-parse) or inside a centralising package (DefinitelyTyped, i'm surprised to not found any package.json inside this repo), or both ?

**Comment by andy-ms** [comment]
We recommend [bundling](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) types if possible. That would ensure that the types reflect the correct version of the library, and users only have to install one package.
The reason there's no `package.json` for DefinitelyTyped is that it represents many packages, one per directory, and the packages are generated automatically from the definitions.

**Comment by wdavidw** [comment]
It makes sense. Any help will be appreciated to ensure the types are correctly integrated with this package and associated to some tests.

**Comment by sbking** [comment]
@wdavidw The current definitions use `any[][]` for the stringify input parameter. This means you can't use an array of objects, since `object` is not assignable to `any[]`, and therefore `object[]` is not assignable to `any[][]`. Perhaps this could be changed to `any[][] | object[]` ?

**Comment by robbyemmert** [comment]
Any progress on this? I would love to see types bundled with this package. It would make this lib a lot easier and safer to use.

**Comment by wdavidw** [comment]
There have been some progress, not everything is typed yet but the most important modules are, for example:

* [csv-generate](https://github.com/adaltas/node-csv-generate/tree/master/lib)
* [csv-parse](https://github.com/adaltas/node-csv-parse/tree/master/lib)
* [csv-stringify](https://github.com/adaltas/node-csv-stringify/tree/master/lib)

It is still uncomplete and help would be appreciated. The type definitions are also tested, for example in [csv-parse](https://github.com/adaltas/node-csv-parse/blob/master/test/api.types.ts).

**Comment by wdavidw** [comment]
Doing some cleanup.
