### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by ylwshzh** [adaltas/node-csv#225]
I tried parsing a big file(almost 200M),  and the node process crashed. I got 'FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory'. I used the version 0.4.6.

==== JS stack trace =========================================

Security context: 0x3f29f6cc9e59 <JS Object>
    2: /* anonymous */ [/Users/george/git/Compass-ETL/node_modules/csv-parse/lib/index.js:~53] [pc=0x2dc399f3ff2f] (this=0x38a5af104db9 <JS Object>)
    3: emit [events.js:~136] [pc=0x2dc399f40721] (this=0x38a5af104db9 <JS Object>,type=0x3f29f6cd0b61 <String[8]: readable>)
    4: readableAddChunk(aka readableAddChunk) [_stream_readable.js:~143] [pc=0x2dc399f3e4e5] (this=0x3f29f6c04189 <undefine...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Abort trap: 6

**Comment by wdavidw** [comment]
First time we've seen this error, the file isnt particularly big, anything special inside ? Could you try with some smaller chunk to confirm it is due to the size ?

**Comment by ylwshzh** [comment]
I forgot to tell an import thing: when my node process was running, the memory grew fast and finally it caused memory leak. That's the reason behind. 
I also tried with a smaller chunk(40MB), it successed because the memory didn't grow to leak.
Here is my code:
`fs.readFile('./1012_log.csv', 'utf8', (err, data) => { 
    if (err) {                                         
        return cb(err);                                
    }                                                  
    csv.parse(data, (err, d) => {
        if (err) {
            return cb(err);
        }
        console.log('get data');
        // Do sth.                                     
        cb(null);
    });     
`

**Comment by wdavidw** [comment]
By running `fs.readFile('./1012_log.csv', 'utf8', (err, data) =>`, you're putting all your file into memory. Instead you should use:

```
fs.readFile('./1012_log.csv', 'utf8').pipe(csv.parse(opts)).pipe ...
```

**Comment by ylwshzh** [comment]
Thanks very much. I resolved the problem by using the stream api.

**Comment by nachimehta** [comment]
@wdavidw , I've got a similar issue, but I seemed to have solved it. I was hoping you can educate me as to why I had a problem though. My initial code looked like this:

```
var parser = parse({relax_column_count: true}, function(err) {
  if(err) {
    console.log(err);
  }
});

var transformer = transform(function(record, callback) {
  callback(null, writeLine(record));
}, {parallel: 10});

pool.connect(function(err, client, done) {
  var dbstream = client.query(copyFrom('COPY my_table FROM STDIN WITH (FORMAT csv, DELIMITER \',\', HEADER)'));
  dbstream.on('end', done);
  dbstream.on('error', function(err) {
    console.log(err);
  });

  request(downloadOptions).pipe(parser).pipe(transformer).pipe(dbstream);
});
```

With this code, I was getting a memory leak at the pipe into the parser. I proved this by changing piping configurations and watching `top`. Once I removed the callback function in the parser declaration, the memory leak went away:

```
var parser = parse({relax_column_count: true});
```

If you have a little insight, would love to hear it. Thanks.

**Comment by nachimehta** [comment]
Should I be using `parser.on('error', error => {console.log(error)})` or something like that instead?

**Comment by wdavidw** [comment]
Yes, by putting the callback function, you are forcing the parser to load all the record in memory to fullfill the callback 2nd argument (the data) which remove all the benefits of streaming.
