### ISSUE TITLE
Cannot import module 'csv'

### ISSUE THREAD

**Issue by saylerb** [adaltas/node-csv#230]
I bumped my version to 3.0.0 and now I'm getting this error: Cannot find module 'csv'. Downgrading to 1.0.0 fixes the problem however.

EDIT: 
I noticed that there's no `/lib/index.js` in the distributed package anymore. Does that mean that we cannot import as `const csv = require('csv')` anymore? Do we need to import the individual modules as needed?

**Comment by rehansheikh** [comment]
Installed version 3.0.0 and import works fine if I do `const parser = require('csv-parse');` but `const csv = require('csv')` does not work for me either.

**Comment by wdavidw** [comment]
It was a mistake in the release procedure, pb is fixed with version 3.0.2
