### ISSUE TITLE
Changelog from v1 to v3

### ISSUE THREAD

**Issue by joelmukuthu** [adaltas/node-csv#231]
Hi,

Sorry if I'm missed something but I'm trying to figure out why the version went from 1x to 3x. Are there some tags missing in github? Or if v2 was intentionally skipped would it be possible to add a small note in the changelog pointing that out?

And thanks for working on this, great module!

**Comment by wdavidw** [comment]
There was a version 2. The versions of the package are driven by its 4 dependencies. Any major upgrade in one of those involve a major upgrade to this package.
