### ISSUE TITLE
Tutorial for beginners

### ISSUE THREAD

**Issue by huy-nguyen** [adaltas/node-csv#232]
Thanks for writing this great library. I've been using it to process the IMDb movie data set and this library is probably the best one for csv handling on NPM. However, when I first tried it out, the documentation can be a bit confusing (especially to someone who hasn't used NodeJS's `stream`s like me) so I wrote a very short tutorial with accompanying explanation and unit tests so that newcomers to the package will be able to more quickly get acquainted with this library. 

Are you open to adding a link to my short tutorial to the package's documentation? Feel free to check it out [here](https://www.huynguyen.io/2018-05-streaming-conversion-csv-tsv-json/)

**Comment by wdavidw** [comment]
Thank you. I will not provide any external link but you are welcome to integrate the content of your tutorial into the [official website](https://github.com/adaltas/node-csv-docs) as a pull request.
