### ISSUE TITLE
Have transform layer write two rows?

### ISSUE THREAD

**Issue by JohnONeill** [adaltas/node-csv#234]
I'm trying to take a CSV — that contains certain column headers / labels and some input data — and output to a CSV with those same headers _plus_ additional headers; the tricky part is that I don't know what those additional headers will be until I process the first row of input data. 

In other words, I'm trying to:
- Read the first row (to grab the headers)
- "Skip" in the transform layer (we don't write anything to the output file just yet)
- Read in the second row (now actual input data)
- Write out the new column headers, which will be the original headers _plus_ additional headers that are computed from input data

The problem is that by "skipping" that first row, I'm always rendering "one row behind", so I'm unable to write out the final row.

Is there a way to pull this off? If the transform layer / function was able to write two records at a time, but that would be one-way, but it's probably not built for something like that right? I feel like I'm approaching it in completely the wrong way, but it's a little hard to see the forest for the trees at this point.

Thanks!

**Comment by wdavidw** [comment]
Not sure if it will help be you could have a look at the [stream-transform](https://github.com/adaltas/node-stream-transform/) project.

**Comment by JohnONeill** [comment]
Ah, I was using the transform library, but somehow I missed `Generating multiple records is only supported in asynchonous mode by providing n-arguments after the error argument instead of simply one.` in the docs. Thanks @wdavidw! 🙏
