### ISSUE TITLE
Where to define filename

### ISSUE THREAD

**Issue by mesqueeb** [adaltas/node-csv#235]
I'm really sorry for this question, I'm rather new to nodeJS. I have worked a little with fs before.

I failed to find out from the readme where to define the filename to write to.
I assume we need to define a writableStream?
```js
writableStream = fs.createWriteStream('./export.csv')
```
But where do we connect this to the csv app?

Thanks so much!!

**Comment by wdavidw** [comment]
The CSV parser and stringifier as well as the `fs.createWriteStream` return a Node.js Stream. This means you can pipe a Stream Reader to a Stream Writer.

```js
parse = require('csv-parse')
fs = require('fs')
parse(data).pipe(fs.createWriteStream('./export.csv'))
```

or 


```js
parse = require('csv-parse')
stringify = require('csv-stringify')
fs = require('fs')
fs.createReadStream(a_file)
.pipe(parse(options))
.pipe(stringify(options))
.pipe(fs.createWriteStream('./export.csv'))
```

**Comment by nnti3n** [comment]
Should add this to sample code, not everyone familiar with Node

**Comment by mesqueeb** [comment]
@wdavidw I agree, Your explanation and code samples were very clear and that was what I need to be able to work with node-csv. So I would advise to maybe add this to the readme for newbies like me. : D
