### ISSUE TITLE
csv.adaltas.com is heavy

### ISSUE THREAD

**Issue by zacintosh** [adaltas/node-csv#237]
is heavy. is heavy. is heavy.
504 Gateway Time-out

**Comment by wdavidw** [comment]
It seems fine from here. Are you still experiencing a slowdown ?

**Comment by zacintosh** [comment]
Thank you for your reply. There is no problem right now.
Yesterday too, the server was heavy in that hour, so I'll try to access it again tomorrow.

**Comment by zacintosh** [comment]
I can't access csv.adaltas.com at this time. There is no server error message.
The browser message is "refused on csv.adaltas.com. ERR_CONNECTION_REFUSED"

I access from Japan. Isn't it allowed to see in this time?
I would want to read the details at any time.

**Comment by wdavidw** [comment]
The server shall be available 24h. It seems like the server suffer from heavy load, i'm currently investigating

**Comment by zacintosh** [comment]
now, no problem.
