### ISSUE TITLE
Question about which API to use

### ISSUE THREAD

**Issue by mcmillhj-wta** [adaltas/node-csv#238]
We are currently using node-csv to parse CSVs files for our project and apply business logic to each row. I believe we have made some mistakes in how we have set the parser up and was hoping to get some ideas about where we went wrong. 

Currently our parsing loop looks like this: 

```
return new Promise((resolve, reject) => {
      return fs
        .createReadStream(this.filename)
        .pipe(
          csv({
            columns: data =>
              data.map(
                (d: string) => (this.columnMap[d] && this.columnMap[d].to) || d
              )
          })
        )
        .on("data", (row: object) => {
          line++;
          // apply lots of business logic here 

          // save out row
          rows.push(row);
        })
        .on("error", (error: Error) => {
          errors.push(`Line ${line}: ${error}`);
        })
        .on("end", async () => {
          // clean up file after upload
          await fs.unlink(this.filename, err => {
            if (err) {
              throw err;
            }
          });

          resolve(rows);
        });
    });
```

When using this approach with a larger file, ~1000 rows it appears to just hang and never get to the `on("data", ....)` handler. So I have two questions: 

1. Where have we gone wrong here? 
2. What would be the appropriate API for us to use given that we want to apply business logic for each row? 

Please let me know if I can clarify in anyway. 

Thanks.

**Comment by wdavidw** [comment]
The preferred way to apply business logic for each row is to pipe the result of the parser to an instance of stream-transform. Could you try this way out and let us know how that work for you.

**Comment by mcmillhj-wta** [comment]
Actually, I think there may have been an issue with the input file. After validating it more carefully the 1000 row file parsed in less than one second. 

I still feel I may be using the API incorrectly though :\

**Comment by wdavidw** [comment]
I personally never use the `data` event but always the `readable` event. This is the one used in the documentation. Your usage seems ok even if I would have written it differently (not tested), but this is all about personal taste:

```js
return new Promise((resolve, reject) => {
  fs
  .createReadStream(this.filename)
  .pipe(
    parse({
      columns: data =>
        data.map(
          (d: string) => (this.columnMap[d] && this.columnMap[d].to) || d
        )
    }, function(err1, records){
      fs.unlink(this.filename, function(err2) {
        if(err1 || err2) return reject(err1 || err2)
        resolve(records)
      })
    })
  )
})
```
