### ISSUE TITLE
stringify: field containing line breaks(CRLF) are not quote escaped

### ISSUE THREAD

**Issue by shusson** [adaltas/node-csv#241]
Based on https://tools.ietf.org/html/rfc4180 2.6

> 6.  Fields containing line breaks (CRLF), double quotes, and commas
>       should be enclosed in double-quotes.  For example:

Example:
```
const output = stringify(["I\nLove\nLamp"], {
    delimiter: ",",
    rowDelimiter: "\r\n"
});
```

Expected output:
```
"I
Love
Lamp"
```

Actual:
```
I
Love
Lamp
```

**Comment by wdavidw** [comment]
We interpret the CSV specification slightly differently: Fields containing row delimiters, quote characteres, escape characters, and field delimiters should be enclosed in quote characters. Now, the question is: does "\n" is considered to be one of those if row delimiter is "\r\n" ? Or it could be rephrase more generally as: does a field with a part of the raw delimiter should be quoted ?

**Comment by shusson** [comment]
Yeah I raised a similar issue with https://github.com/SheetJS/js-xlsx/issues/1330 which is following Excel logic.

Taking a step back from the spec, I'd like to think that changing the row delimiter format wouldn't affect the writing or parsing of the fields. 

To give a bit of context. We are creating CSVs from external data and we have some requirements for the format of the CSV depending on the user (e.g row delimiter needs to be "\r\n").

**Comment by wdavidw** [comment]
Wouldnt it be appropriate in your context to use the `quoted` or `quotedString` options ?

**Comment by shusson** [comment]
yeah we could also do that, but we would prefer to only quote when required.

**Comment by wdavidw** [comment]
I'm trying to thing of an appropriate evolution. Do you have any suggestions ? Maybe an option `quotedIfContains` or `quotedIfMatch` which would accept a string, a regexp or an array of both ?

**Comment by shusson** [comment]
My suggestion would be to always escape quote fields that contain any CRLFs. Regardless of the row delimiter. An option sounds reasonable though and would cover our use case.

**Comment by wdavidw** [comment]
The latest version 5 of csv-stringify introduce the `quoted_match` option which shall solve your issue. Feel free to re-open if not.

**Comment by sthuber90** [comment]
@shusson were you able to come up with a solution and how does it look like?

**Comment by shusson** [comment]
@sthuber90  we ended up doing https://github.com/SheetJS/js-xlsx/issues/1330#issuecomment-434093061
