### ISSUE TITLE
using on("skip" function(err){}) to return line number and line text

### ISSUE THREAD

**Issue by noodlespace** [adaltas/node-csv#243]
I am trying to retrieve the line number and the lines text that csv-parse has encountered an error at, so far I am getting the line number from `parser.info.lines`, but I am struggling to find the buffer that was read

Any help would be greatly appreciated

**Comment by wdavidw** [comment]
Did you try `parser.state.rawBuffer` ?

**Comment by noodlespace** [comment]
I have, I just get an empty buffer at that point

**Comment by noodlespace** [comment]
I set `raw: true`

Only problem now is that I get half the record up until the field it errors out on,
Text: "000000000000","ASTON SMITH"","A ","SMITH"","","ASTON"
Raw Buffer: ""000000000000","ASTON SMITH"",""

**Comment by noodlespace** [comment]
For anyone that is still wondering, if you ignore "Invalid Closing Quote:" errors, the next error will include an "Invalid Record Length" error that will include the full raw buffer

**Comment by wdavidw** [comment]
Sorry, i didn't had the time to investigate further in the last few days.
