### ISSUE TITLE
BOM option does not remove BOM

### ISSUE THREAD

**Issue by mariuspopovici** [adaltas/node-csv#245]
I have a .CSV file with BOM. I tried using the "bom" option to strip it but it doesn't seem to work. I ended up manually replacing it (.replace(/^\uFEFF/, '')) BOM and that fixed the issue but this probably indicates that the option does not work.

Calling code and file attached.
`

    this.csv = require('csv-parse');
    ......
    parse(content, callback) {
      let _this = this;
      this.csv(content, { 
        bom: true,
        columns: true, 
        trim: true,
        skip_empty_lines: true,
        cast: function(value, context) {
          switch (context.column) {
            case 'time':
              return _this.parseTime(value);
            case 'power':
            case 'lap':
              return parseInt(value);
            case 'speed':
            case 'airspeed':
            case 'lat':
            case 'long':
            case 'elevation':
              return parseFloat(value);
            default:
              return value;
          }
        },
      }, (err, records) => {
        if(err) {
            return callback(err, null);
        } else {
            let result = this.validate(records);
            if (result.isValid) {
              return callback(null, this.fit(records));
            } else {
              return callback(new Error(result.message), null);
            }
        }
      });
    }`

[mycdatest.zip](https://github.com/adaltas/node-csv/files/3060179/mycdatest.zip)

**Comment by wdavidw** [comment]
You code is not readable, please format it.

**Comment by mariuspopovici** [comment]
Sorry... Not sure why it's not formatting it correctly. Seems to be OK now.

**Comment by wdavidw** [comment]
This seems to work for me:

```js
const assert = require('assert')
const fs = require('fs')
const parse = require('csv-parse')
fs
.createReadStream('./mycdatest.csv')
.pipe(parse({bom: true, skip_empty_lines: true}, (err, data) => {
  assert(err === undefined)
  assert.strictEqual(err, undefined)
  assert.strictEqual(data[0][0], "speed")
}))
```

Make sure you are release version 4.4.0, this feature was realease 2 days ago. I will update the website for the bom option to reflect that information.

In the future, please simplify the provided code to the maximum. It takes time to support end users of a package and most of your options are not relevant to this issue, see my example above for inspiration.

I'll let you close this issue if my answer fixed your problem.

**Comment by mariuspopovici** [comment]
Thanks! I was still on the previous version. I upgraded now and it works fine. I thought the feature has always been there.
Thanks again.
