### ISSUE TITLE
Rewrite in TypeScript

### ISSUE THREAD

**Issue by ffflorian** [adaltas/node-csv#249]
Hi @adaltas what do you think about rewriting the package in TypeScript? I'd like to do it but wanted to ask you first if you would even want that to avoid unnecessary work.

// cc @wdavidw

**Comment by wdavidw** [comment]
I believe TypeScript as great advantages for much larger projects. For small project like this one, I dont see much benefits and I actually prefer Coffee for its readability. I think using JavaScript is much more appropriate at the moment. But there is a need to add TS declaration to this package, all the other packages have it but this one (csv-transform, csv-parse, csv-stringify, stream-transform). I've actually started but I didnt find how to make it work, it shall look like this (but it doesnt work !):

```ts
import * as generate from "csv-generate/lib/index";
import * as parse from "csv-parse/lib/index";
import * as transform from "stream-transform/lib/index";
import * as stringify from "csv-stringify/lib/index";

export csv;

interface csv {
  generate: generate,
  parse: parse,
  transform: transform,
  stringify: stringify,
}
```

**Comment by ffflorian** [comment]
Alright, I'll open a PR for that.

**Comment by wdavidw** [comment]
I'll push you my initial code in a branch, there are the basis to write the test as well and follow the approach of the other packages.

**Comment by wdavidw** [comment]
OK, see the [ts_definition](https://github.com/adaltas/node-csv/tree/ts_definition) branch.
