### ISSUE TITLE
Example of file input?

### ISSUE THREAD

**Issue by rjvehn** [adaltas/node-csv#251]
This is a great project, but I must be an idiot because I can only find examples of using CSV input from the csv-generator package, not from a CSV file. And since the parse package only seems to accept an already read CSV array, it seems to require Node to have already read the CSV into memory, which kind of limits the point of the stream-processing, right?

Is there an example of handing a CSV file handle to the parser, so that it doesn't trigger reading the whole at once?

Sorry for the stupid question, I am sure it is answered in the documentation, but I do not know where.

**Comment by wdavidw** [comment]
All the csv project accept stream reader as input and stream writer as output, thus this is more a Node.js question about you to connect stream toguether. Replace `input = generate()` by `input = fs.createReadStream`.

**Comment by rjvehn** [comment]
@wdavidw thank you so much! I knew it was something simple I screwed up.
