### ISSUE TITLE
How to handle errors

### ISSUE THREAD

**Issue by ed-sparkes** [adaltas/node-csv#253]
Hi, 

This is a question more than an issue. What is the best way to handle errors?

When parsing a row i want to error if the row is corrupt, i want to be able to catch this error somewhere ? 

```
 parser.on('readable', () => {
        let record

        while ((record = parser.read())) {
          const {lines, records} = parser.info
          if (!record.myfield|| record.myfield.length ===0){
            throw new Error(`Record ${records} has no myfield`)
          }
          
      })
```
 

I have tried ther on error but this is not being hit 
```
    parser.on('error', err => {
        console.log("Where is this error going 1")
        console.error(err.message)
      })
```
i have tried a try catch block around end 

```
  const end = new Promise((resolve, reject) => {
        parser.on('end', () => resolve(parser.read()))
        parser.on('error', reject)
        readStream.on('error', reject)
      })
      try {
      await end;
      }catch (error){
        console.log("Where is this error going 2")
      }
```

but this is not hit either

Any thoughts 

Thanks, Ed

**Comment by wdavidw** [comment]
I would say that your sample is not handle by our package but by the Node.js stream API which handle that part. I'll try to reproduce..

**Comment by wdavidw** [comment]
This is an anwer as well as potentially a new issue:

First I have tried to reproduce your issue with the native API of Node.js using *fs* and *stream*, the behavior is consistent with what you are observing:

```js
const fs = require('fs');
fs.writeFileSync(`${__dirname}/sample_fs.csv`, 'a,b,c\n1,2,3')
const reader = fs.createReadStream(`${__dirname}/sample_fs.csv`, {highWaterMark: 1})
reader.on('readable', () => {
  let data
  while ((data = reader.read())) {
    throw new Error("Catch me")
  }
})
reader.on('error', (err) => {
  console.log(`Oh yes: ${err.message}`)
})
reader.on('end', () => {
  console.log("Oh no!")
})
```

The output shows that the error is not handled by the API, implied that it is the responsibility of the developer:

```
/Users/wdavidw/projects/github/csv/csv-parse/sample_fs.js:7
    throw new Error("Catch me")
    ^

Error: Catch me
    at ReadStream.<anonymous> (/..../sample_fs.js:7:11)
    at ReadStream.emit (events.js:203:13)
    at emitReadable_ (_stream_readable.js:558:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

```

That lead me to find an appropriate way to handle it. Calling `destroy` with the error as argument seems just fine with the sample above:

```js
const fs = require('fs');
fs.writeFileSync(`${__dirname}/sample_fs.csv`, 'a,b,c\n1,2,3')
const reader = fs.createReadStream(`${__dirname}/sample_fs.csv`, {highWaterMark: 1})
reader.on('readable', () => {
  let data
  while ((data = reader.read())) {
    reader.destroy(new Error("Catch me"))
  }
})
reader.on('error', (err) => {
  console.log(`Oh yes: ${err.message}`)
})
reader.on('end', () => {
  console.log("Oh no!")
})
```

Since it prints:

```
Oh yes: Catch me
```

However, calling `destroy` inside the CSV parser is not consistent with the behavior observed in "fs", it will both emit the *end* and *error* events:

```js

const parse = require('.');
const parser = parse('a,b,c\n1,2,3')
parser.on('readable', () => {
  let record
  while ((record = parser.read())) {
    parser.destroy(new Error("Catch me"))
  }
})
parser.on('error', (err) => {
  console.log(`Oh yes: ${err.message}`)
})
parser.on('end', () => {
  console.log("Oh no!")
})
```

Will print:

```
Oh yes: Catch me
Oh no!
```

**Comment by ed-sparkes** [comment]
Great thanks, I can now successfully catch my errors reject the promise and handle as appropriate which is great. 

I think i may be using it wrongly though (not in a stream) as the values of the info properties lines and records are the full number of lines for the whole file not infringement with each line read. 

Also the console.log statement `console.log(`${lines} - ${records}`)` is being called for each row even if the first row errors and the promise is rejected. 

Please see my code below. Any thoughts greatly appreciated


```
const readStream = s3Client.getObject(params).createReadStream()
const parser = csvparse({
    delimiter: ',',
    columns: true,
})

parser.on('readable', () => {
    let record
   
    while ((record = parser.read())) {
     try{
      const { lines, records } = parser.info
      console.log(`${lines} - ${records}`)
      if (!record.myField || record.myField.length === 0) {
        throw new Error(`Record ${records} has no myField`)
      }

    }catch(error){
      parser.destroy(error)
    }
    }
  })

  readStream.pipe(parser)

  const end = new Promise((resolve, reject) => {
    parser.on('end', () => resolve(parser.read()))
    parser.on('error', err => {
      console.log('Where is this error going 1')
      console.error(err.message)
      reject(err)
    })
    readStream.on('error', reject)
  })
  try {
    await end
  } catch (error) {
    console.log('Where is this error going 2')
    throw error
  }
```

**Comment by wdavidw** [comment]
> Also the console.log statement console.log(${lines} - ${records}) is being called for each row even if the first row errors and the promise is rejected.

This is not related to the parser but how the native Node.js stream is handling the readable event. We don't have much control over it. It seems that you must stop the parser/stream reader if you catch an error.

**Comment by wdavidw** [comment]
As for the usage of `info`, it seems ok but I don't fully get your probleme. If you think there is a bug, you can open a new issue with a minimal sample illustrating it.

**Comment by ed-sparkes** [comment]
hmm perhaps a misunderstanding on my part, i was expecting the info to increment one per record but it seems it increments once per chunk in the underlying read stream, seeing as s3 readstream pipes the http response im guessing it doing it in chunks of a certain number of bytes rather than rows in the source csv and so the info updates in blocks, i.e for the first 500 records the lines and records might be 500 and then from there to the end say 700 rows the values will all be 700

**Comment by wdavidw** [comment]
This is because you are inside the 'readable' call and, for performance reason, it is called in batch of records. Nothing you can do (at least without degrading the performance significantly)
