### ISSUE TITLE
Documentation / website unavailable?

### ISSUE THREAD

**Issue by darklajid** [adaltas/node-csv#256]
The npm package and Readme link to https://csv.js.org/ which - at the time of this writing - ends up at a Github 404 saying "There isn't a GitHub Pages site here."

The repository itself has http://csv.adaltas.com/ in the description, but (again, at the time of this writing) that returns an NXDOMAIN result, the DNS entry doesn't exist.

Where's the right location to read about the library?

**Comment by wdavidw** [comment]
csv.adaltas has been moved to csv.js.org and shall be corrected. I just find 2 occurences left in the csv-stringify module but let me know where you saw this domain. The website shall be up now, I manually run a deployment script by mistake.

**Comment by darklajid** [comment]
It's in the repository description/header itself above the tags.
"Full featured CSV parser with simple api and tested against large datasets. http://csv.adaltas.com"

**Comment by wdavidw** [comment]
Fixed, thank you.
