### ISSUE TITLE
SCRIPT1028 error with spread syntax on Edge

### ISSUE THREAD

**Issue by david-pfx** [adaltas/node-csv#257]
SCRIPT1028: Expected identifier, string or number 

This is the code that triggers the error. Note the spread syntax, apparently not supported in Edge. Works fine with Firefox and transpiled in Node.

```
class Parser extends Transform {
  constructor(opts = {}) {
    super({ ...{
        readableObjectMode: true
      },
      ...opts
    });

```

**Comment by wdavidw** [comment]
You should use the "es5" modules, such as `require('csv/es5')` and `require('csv/es5/sync')`. Feel free to improve the doc if this isn't clear enough.

**Comment by david-pfx** [comment]
Thank you, that seems to fix the problem.

Edge is not an "older browser", it's the current release on Windows 10. Perhaps your documentation should recommend the ES5 variant as the default for in-browser use, unless developers are certain their target users are all using a browser that fully supports ES6.
