### ISSUE TITLE
csv-stringify does not escape row delimiter(s) inside a field

### ISSUE THREAD

**Issue by fbx31** [adaltas/node-csv#258]
I think, but perhaps I am wrong, that end of line characters (row delimiters) within a field must also be escaped.
Correct me if I am wrong but the current library is not doing that (according to the escape option description).
thanks

**Comment by wdavidw** [comment]
If I understood well, `record_delimiter` is escaped, see [this test](https://github.com/adaltas/node-csv-stringify/blob/master/test/option.escape.coffee#L48-L56). Feel free to re-open if I didn't understood well the issue

**Comment by fbx31** [comment]
Hello
This is my current configuration
    const stringifier = stringify({
        delimiter: ';',
        header: true,
        escape: '"',
        quote: '"',
        quoted: true,
        cast: {
            date: (value) => { return { value: value.toISOString() }; }
        }
    });
The row delimiter used is LF but there are some objects string fields containing LF too.
With my configuration, I would expect to get the quote char before the inner LF char of the string fields but it's not the case.
I got something like:
"my title", "my text field"<LF>
"my title2", "my text field<LF> with LF inside"<LF>
instead of expected:
"my title2", "my text field"<LF> with LF inside"<LF>
Am i wrong?

**Comment by wdavidw** [comment]
Could you please format your comment in markdown such that code is readable. Also, take inspiration from the [test](https://github.com/adaltas/node-csv-stringify/blob/master/test/option.escape.coffee#L48-L56) I sent you to provide a working exemple of what you are expecting with not only the output and option you use but also the input.
