### ISSUE TITLE
csv stringify seems to be replaceing dates

### ISSUE THREAD

**Issue by ryanlsmith4** [adaltas/node-csv#259]
csv.stringify appears to be replacing dates with time since the unix epoch. 
<img width="161" alt="Screen Shot 2020-03-03 at 5 52 00 PM" src="https://user-images.githubusercontent.com/36646424/75830928-bb1db880-5d77-11ea-9ffd-727ce3cc4a2f.png">

Where those numbers are dates but in a format that is the time since the unix epoch.

Is there a work around somehow?

**Comment by wdavidw** [comment]
See the [`cast.date` option](https://csv.js.org/stringify/options/cast/#date). It allows you to define a custom conversion function.
