### ISSUE TITLE
Could we use it to parse csv file in browser env and how to use it?

### ISSUE THREAD

**Issue by oushu1zhangxiangxuan1** [adaltas/node-csv#260]
Acctually I got some errors below in an brower env:

```
![image](https://user-images.githubusercontent.com/39079736/77813395-38bcb600-70e3-11ea-93c5-2710b543957f.png)

```

**Comment by wdavidw** [comment]
You can do it behind webpack or similar. For example, the [csv.js.org](https://csv.js.org) website is build with [Gastby](https://www.gatsbyjs.org/) and I had nothing to set up to have it work with the [CSV convertor tool](https://csv.js.org/convert/).
