### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by darkguy2008** [adaltas/node-csv#261]
I'm trying to follow the CSV examples but it's not working... it says:
```
TypeError: csv.parse.default is not a function
```
My only (relevant) code is:
```
import * as csv from 'csv';
const strcsv = fs.readFileSync('C:\\Temp\\file.csv', 'utf-8');
const parser = csv.parse.default(strcsv, {}, a => {
            console.log(a);
        });
```

Also with sync, the same error happens:
```
TypeError: csvSync.parse.default is not a function
```
In this code:
```
import * as csvSync from 'csv/lib/sync';
        const strcsv = fs.readFileSync('C:\\Temp\\file.csv', 'utf-8');
        const a = csvSync.parse.default(strcsv, {});
        console.log(a);
```

Any ideas? The documentation isn't very helpful when it comes to TS...

Thanks!

**Comment by wdavidw** [comment]
You are certainly welcome to improve the documentation. I have personally no interest nor knowledge in TS so this is mostly community managed. Where did you read about `parse.default`, it doesn't exist as you have experienced. I can't find where you found something about it.

**Comment by darkguy2008** [comment]
Thanks for your response @wdavidw . That's interesting though, as there's a lot of similarities between TS and JS and a lot of frameworks are using TS nowadays. 

Anyways, for future readers, I was able to get it working by using the sync API like this:

```
import * as csv from 'csv/lib/sync';

// Load
const strcsv = fs.readFileSync(csvFilename, 'utf-8');
const data = (csv.parse as any)(strcsv , {
    bom: true,
    cast: false,
    columns: true
});

//Save
fs.writeFileSync(outputFilename, (csv.stringify as any)(rv, { header: true, quoted: true }), 'utf-8');
```

The .default function is something that Typescript has by default. I'm not really sure why, it seems to be related to importing a function that is not a class, so the .default is just like calling the function itself (similar to fn.apply(), I'd say). I don't really have an official explanation but that's what I get from experience.

There's definitely some need for TS in the documentation though, and although I'd love to improve it I'm way too busy but this is the most I can do for others who might stumble upon the same issue. This should be something good to add to the documentation maybe by another passerby someday :)

**Comment by wdavidw** [comment]
Thank you for your reply. To answer your question about JS versus TS, it gives me a lot of headaches for very little benefit, it brakes my development productivity and if I had to go with a typed language, I will choose another one. Personal preference. Maybe I'll change my point of view one day and I am very happy to support TS in my libs whenever I am asked for it.

I wonder why you have to go through so much pain, this is expected to work:

```ts
import * as parse from 'csv-parse/lib/index'
parse("c,s,v", function(err: Error, data: object, info: parse.Info){
  if(err !== undefined){
    data.should.eql([['a'], ['b']])
    info.records.should.eql(2)
  }
  console.warn(err)
})
```

or with the sync API:

```ts
import * as parse from 'csv-parse/lib/sync'
try {
  const data: object = parse("c,s,v")
  // handle data
}catch (err){
  // handle error
}
```

**Comment by GuusBaggen** [comment]
This works for me in typescript

`
import parseCSV from "csv-parse/lib/sync";
const parsed = parseCSV(data);
`

**Comment by wdavidw** [comment]
Maybe I can close in such case.

**Comment by douglasg14b** [comment]
This doe snot work for me.

> Cannot find module 'csv-parse/lib/sync' or its corresponding type declarations.ts(2307)
