### ISSUE TITLE
Type 'typeof stringify' has no call signatures.

### ISSUE THREAD

**Issue by vicary** [adaltas/node-csv#262]
It looks like the way this package re-exports `csv-stringify` is masking its *default* type i.e. `export = stringify`.

**Comment by wdavidw** [comment]
Could you clarify?

**Comment by vicary** [comment]
Not sure how it differs between two module systems, but here's how it works.

If I do `import stringify from "csv-stringify"` TypeScript picks it up correctly, autocompletion and eslint likes it, but `import { stringify } from "csv"` marks error `Type 'typeof stringify' has no call signatures.` on all references of `stringify(...)`.

So I suspects that the way `csv` does `import * as stringifyImport from 'csv-stringify';` and the way `csv-stringify` does `export = stringify` somehow messes up the default import in the type system.

**Comment by vicary** [comment]
If I edit `csv/lib/index.d.ts` from 

```typescript
import * as stringifyImport from "csv-stringify";
export var stringify: typeof stringifyImport;
```

into 

```typescript
export * as stringify from "csv-stringify";
```

it can correctly picks up the call signature.

**Comment by wdavidw** [comment]
You must use `import {stringify} from 'csv'`. Feel free to update the documentation, a new page covering TypeScript could be handy. I don't use it enough to handle it.

**Comment by vicary** [comment]
This issue itself is originating from the use of `import { stringify } from "csv"`, one possible fix is to change the `index.d.ts` like my comment above.

If there is no compatibility concerns, I can make a PR for that.

**Comment by wdavidw** [comment]
Then I don't understand the issue. Could you help me reproduce :

> `import { stringify } from "csv"` marks error `Type 'typeof stringify' has no call signatures.` on all references of `stringify(...)`.

Look at [this test](https://github.com/adaltas/node-csv/blob/master/test/api.types.ts). It uses `transform` and could be extended to use `stringify`. Please, help me understand and reproduce the issue.

**Comment by vicary** [comment]
Oh I should add that there is no runtime error on this one.

Only the linter in VS Code and our CI pipeline yells at me about this, and unfortunately my team does not allow lint errors on production.

my current options are,

1. @ts-ignore and brace myself in the next meeting
2. Change the `index.d.ts` here
3. directly depends on `csv-stringify`

**Comment by wdavidw** [comment]
Opening the project inside VS Code doesn't complain with warning. I am not against importing your changes but I am not a Typescript user and I can't reproduce the error. Could you provide me with instructions on how your VS Code is configured? Does anyone familiar with TypeScript could validate #264?

**Comment by vicary** [comment]
# Steps to reproduce
1. `import { stringify } from "csv";`
2. Anywhere in VS Code you invoke `stringify(...)` will show the warning in this image  \
    ![Screenshot 2020-07-06 at 9 30 17 PM](https://user-images.githubusercontent.com/85772/86598721-1d115780-bfd0-11ea-9a20-801331145de3.png)
3. My `tsconfig.json` is copied from a default one generated by `create-react-app`
    ```JSON
    {
      "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "declaration": false,
        "esModuleInterop": true,
        "module": "commonjs",
        "moduleResolution": "node",
        "preserveConstEnums": true,
        "strictNullChecks": true,
        "sourceMap": true,
        "target": "es2017"
      }
    }
    ```

**Comment by yang** [comment]
Can confirm, using TS 3.9.7.

**Comment by wdavidw** [comment]
I'll be happy to help but I am short on this. Could someone provide a pull request ?

**Comment by wdavidw** [comment]
Here is what I see when I apply @vicary suggestions:

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/46896/95848673-a7dfbc00-0d4e-11eb-8de7-8b7e1512ecab.png">

**Comment by vicary** [comment]
@wdavidw Yes, because commonjs module is another module system. You may categorize them in two ways:

# CommonJS
```js
module.exports.foo = ...;
module.exports.bar = ...;
// and
const { foo } = require("some_module");
```

# ECMAScript Modules
```js
export default foo;
export const bar = ...;
// and 
import foo from "some_module";
import { default as foo, bar } from "some_module";
```

And because webpack (thus nodejs and react...) wants to transpile ECMAScript Modules into CommonJS such that people can write `import { default as foo } from "some_module"` when their projects in TypeScript, and at the same time supports `const foo = require("some_module");` when the user project is in JavaScript.

This creates an ugly practise of `module.exports = ...` to pretend a *default* export, which only works with `allowSyntheticDefaultImports` enabled in `tsconfig.js` or `jsconfig.js`.

**Comment by wdavidw** [comment]
OK, I understand the source of the problem between the ECMAScript and CommonJS but how to fix it?

**Comment by wdavidw** [comment]
Does replacing `export = stringify` with`export default stringify` in https://github.com/adaltas/node-csv-stringify/blob/master/lib/index.d.ts#L4 will do the trick?

**Comment by vicary** [comment]
> Does replacing `export = stringify` with`export default stringify` in https://github.com/adaltas/node-csv-stringify/blob/master/lib/index.d.ts#L4 will do the trick?

This sounds plausible, but definitely needs tests. Because namespace as not a real thing when transpiling to JavaScript and official TypeScript no longer recommend it.

I would image some version of webpack makes them a real JS object (which creates performance overhead) while latter versions ignoring the whole thing if it's pure types, while refuses to build when there are runtime codes.

**Comment by wdavidw** [comment]
I tried, it brakes the tests inside [test/api.types.ts](https://github.com/adaltas/node-csv-stringify/blob/master/test/api.types.ts)

**Comment by vicary** [comment]
Does enabling `allowSyntheticDefaultImports` works? If so you may document this for future users.

Though there is strong opinions against this in [deno](https://github.com/denoland/deno/issues/7732), making what worked continue to work maybe more important in this case.
