### ISSUE TITLE
Fields enclosed by double quotes

### ISSUE THREAD

**Issue by Vincebe** [adaltas/node-csv#271]
Hello,

I'm trying to parse a (huge) CSV file formatted as follows:

```
"EntityNumber","Data1","Data2","Data3","Data4"
"0211.200.375","006","2008","94910","MAIN"
"0400.078.181","006","2008","46699","MAIN"
"0400.078.181","001","2008","68201","MAIN"
```

What are the right settings?

Thanks

**Comment by wdavidw** [comment]
Have you tried with the default settings before asking us ?

**Comment by Vincebe** [comment]
Yes I have tried everything. But I found the error, it has nothing to do with node-csv...

Sorry
