### ISSUE TITLE
Record length verification is ignored for some files

### ISSUE THREAD

**Issue by rscarson** [adaltas/node-csv#275]
When parsing the clearly invalid string ',,,,,,,,\n,,,\n,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,', no error is triggered, and parser.info reports 3 lines read but 0 records. err is undefined, and an empty array is returned as a result.

Minimal example:

```
const parse = require('csv-parse');

// These are just the options I am using - no combination of options seems to trigger the expected error
parse(',,,,,,,,\n,,,\n,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,', {columns:true, trim:true, skip_empty_lines:true}, (error, json, info) => {
  console.log(error); // will always be undefined
});
```

I am running 4.15.4 behind webpack

**Comment by wdavidw** [comment]
This shall be fixed with commit #eee7e9345b7ffa1b7b15f39ec459af57c9bcbc4f. I will release very soon a new version
