### ISSUE TITLE
Sync API is completely innacessible in native ES Modules

### ISSUE THREAD

**Issue by rayfoss** [adaltas/node-csv#276]
The sync API is not listed in package.json exports or more importantly lib/index.js

The result is there is no standard way to reference lib/sync.js, breaking lots of tools like PNMP, Runkit, Linters, tests, loaders, loggers etc.

https://medium.com/swlh/npm-new-package-json-exports-field-1a7d1f489ccf

While adding sync to index.js would fix it, I would suggest adding index.mjs to properly support named ES Module exports and tree shakers.
https://medium.com/swlh/npm-new-package-json-exports-field-1a7d1f489ccf

Related to https://github.com/adaltas/node-csv/issues/207
Related to https://github.com/adaltas/node-csv/issues/264

**Comment by wdavidw** [comment]
Thanks for your suggestions, I wasnt aware of the import/export properties in package.json and it is very interesting in our context. A few notes/questions:

1. Before upgrading the `csv` package, I wish to first upgrade the other packages such as `csv-parse`. My understanding is that we shall write in ESM first and transpile to CommonJS and old style/browser compatible version from it. I am currently having difficulties to reference an `.mjs` module from the CoffeeScript tests and I wish to keep the tests in Coffee if possible.

2. I have the plan to migrate the CSV related projects into a single monorepo, I might do this before importing your changes.

3. Why do you say the sync modules are not available, you can `require('csv/lib/sync')`, I don't get your point when you write "there is no standard way to reference".

**Comment by rayfoss** [comment]
> 3. Why do you say the sync modules are not available, you can `require('csv/lib/sync')`, I don't get your point when you write "there is no standard way to reference".

Defining exports makes project easier to maintain and more stable by erroring if an undefined entry point is specified. For instance, `require('csv/sec/random.js')` would stop working. That's why defining exports is seen as always being a major semver change... Because of potential wacky wild west undocumented or non standard/semantic access.
