### ISSUE TITLE
Error: 'sync_1.default is not a function'

### ISSUE THREAD

**Issue by gaharrington** [adaltas/node-csv#281]
My code:
```
import parse from 'csv-parse/lib/sync';
...
const csv = fs.readFileSync(filepath, 'utf-8');
const records = parse(csv, {
  columns: true,
  skip_empty_lines: true,
});
```

When the parse() line executes, an error is thrown:
- message:'sync_1.default is not a function'

Versions:
- "csv-parse": "^4.16.0",
- node -v: v12.20.0

**Comment by wdavidw** [comment]
Use CommonJS `require` to load the module. You can look at the [samples](https://github.com/adaltas/node-csv/tree/master/packages/csv-parse/samples). ES6 module are currently being worked on.
