### ISSUE TITLE
Documentation says that recordDelimiter is set to autodiscovery when not set - however, it is not

### ISSUE THREAD

**Issue by rahulgolwalkar** [adaltas/node-csv#282]
**Describe the bug**

Latest version as of today on npm - i.e. 5.5.5

**Observed behavior**
The optional parameter`recordDelimiter` in `parse.Options` is used to separate new records/lines
When not set, as per the documentation, it should auto discover the line separator from either of `['\r\n', '\n', '\r']`. However, that is not the case that is happening. It can handle `\r\n`s however, it fails to recognize `\n` independently as a new line.
Workaround: I explicitly specified `recordDelimiter: ['\r\n', '\n', '\r']` in `options` to make it work.

**Expected Behavior**
When `recordDelimiter` is not specified, the parser should automatically select either of the three values 

**To Reproduce**

Can reproduce on Mac and Linux - not sure on Windows
- Attached is the `win.csv` which just has `\n` as new lines
- try the following code and it will error
```
const csvParser = require('csv')
const fs = require('fs')
const data = fs.readFileSync('./win.csv', 'utf8')
let aaa = csvParser.parse(data, {}, function (err, d2) {
  console.log(d2)
})
```
- to make it work across file types, can just use `recordDelimiter: ['\r\n', '\n', '\r']`

**Comment by rahulgolwalkar** [comment]
[win.csv](https://github.com/adaltas/node-csv/files/6819968/win.csv)

**Comment by wdavidw** [comment]
I run your test with the sourced file without any error.

**Comment by rahulgolwalkar** [comment]
> I run your test with the sourced file without any error. the `\n` is the most common delimiter, it is also used everywhere accross the tests.

Are you using Windows, Mac, or Linux?

**Comment by rahulgolwalkar** [comment]
Hi @wdavidw  , thanks you for looking into this
i think i know why the above file worked smoothly and probably have a some information that might help to debug

The above file worked smoothly cause while uploading the file probably GH made some changes to the encoding and that even works for me. 

So - I created a simple repo which can easily reproduce the issue - https://github.com/rahulgolwalkar/csv_parser_windows_test_delete 

Here, you can see when we add the `recordDelimeter` it works well. 

I would also like to add one more observation - that when I manually added a new line at the end of file - it works as expected. Here is the branch/PR that gets to work without the `recordDelimeter` 
https://github.com/rahulgolwalkar/csv_parser_windows_test_delete/pull/1/files

**Comment by wdavidw** [comment]
The [win2.csv](https://github.com/rahulgolwalkar/csv_parser_windows_test_delete/blob/main/win2.csv) file used for testing contains two record delimiter, `\r\n` and `\r`. When the option is auto-discovered, the first one to appear, `\r\n` in this case, defined the value of record delimiter. The second one, `\r`, is interpreted as any other character. This is why you are getting a `CSV_RECORD_INCONSISTENT_FIELDS_LENGTH`, your record is no longer what you expect.
