### ISSUE TITLE
CSV sync functions won't load

### ISSUE THREAD

**Issue by ed-mauthe** [adaltas/node-csv#289]
**The bug**
CSV/sync won't load due to a syntax error.
Not valid JS, either you're trying to do a ternary or getting the length of options?

```
  if(!Number.isInteger(options?.length)){
                               ^
SyntaxError: Unexpected token '.'

```
**To Reproduce**
`const CSV=require('csv/lib/sync');
`

**Comment by wdavidw** [comment]
Version 5.5.3 of csv shall fix your issue, thank you for reporting.
