### ISSUE TITLE
Repo URL is wrong

### ISSUE THREAD

**Issue by moltar** [adaltas/node-csv#290]
https://github.com/adaltas/node-csv/blob/0fd5209b6862655c384cda052abf38019b959e70/packages/csv-parse/package.json#L48

**Comment by wdavidw** [comment]
This was [fixed in the `package.json` file](https://github.com/adaltas/node-csv/blob/master/packages/csv-parse/package.json#L82-L86) a few weeks ago. Thank you for reporting.
