### ISSUE TITLE
Global object created: `Generator`

### ISSUE THREAD

**Issue by dominykas** [adaltas/node-csv#293]
**Describe the bug**

`csv-generate@3.4.3` seems to be adding a `Generator` global - not sure if that was an intentional change.

**To Reproduce**

See https://github.com/adaltas/node-csv/blob/4f451038ef083b65d58ccee6fe3d041b106cc1cf/packages/csv-generate/lib/index.js#L52

**Additional context**

**Comment by wdavidw** [comment]
Sorry I didn't have much time to get back to you. It seems like [it was fixed](https://github.com/adaltas/node-csv/blob/97a3f58dd73b6452b32cc39511b3ec145fe23c00/packages/csv-generate/lib/index.js#L12) in the meantime.
