### ISSUE TITLE
"data" or "row" event instead of loop in "readable"

### ISSUE THREAD

**Issue by Eric24** [adaltas/node-csv#295]
**Is your feature request related to a problem? Please describe.**
No specific problem, but the loop inside the "readable" event seems a little strange.

**Describe the solution you'd like**
An event that fires when a new row/record is available, which passes the row/record (i.e. "data" or "row").

**Describe alternatives you've considered**
The loop in "readable" works.

**Comment by wdavidw** [comment]
This is native [Node.js Event](https://nodejs.org/api/stream.html#stream_event_readable) behavior, nothing to do on our side.
