### ISSUE TITLE
Documentation mismatch: CSV Parse, Sync API: `csv-parse/lib/sync`

### ISSUE THREAD

**Issue by Toliak** [adaltas/node-csv#299]
**Describe the bug**

[Here](https://csv.js.org/parse/api/sync/) documentation says I should use `import {parse} from 'csv-parse/lib/sync'`.
However, when I am trying to use this like, I capture an error `TS2616: 'parse' can only be imported by using 'import parse = require("csv-parse/lib/sync")' or a default import.`

CSV Parse version: `4.16.3`

**To Reproduce**

Use `import {parse} from 'csv-parse/lib/sync'` line somewhere

**Fix**

If  I use default import `import parse from 'csv-parse/lib/sync'` as TS compiler says, everything is OK

**Additional context**

`npm version` result:
```
{
  'hw-modules': '1.0.0',
  npm: '7.24.1',
  node: '14.15.4',
  v8: '8.4.371.19-node.17',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '83',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1i',
  cldr: '37.0',
  icu: '67.1',
  tz: '2020a',
  unicode: '13.0'
}
```

**One more thing**

GitHub link from the website redirects to the deprecated repo, I would not like to create an entire issue for it :)

**Comment by wdavidw** [comment]
Sorry for the confusion, this page get in as part of the future version which I am preparing. I'll leave it for now as I expect the new version and website to be publish in the next 2-3 weeks.
