### ISSUE TITLE
csv-parse@5.0.1 stream API throws error "list" argument must be an Array of Buffers

### ISSUE THREAD

**Issue by mark-kone** [adaltas/node-csv#303]
**Describe the bug**
Trying to parse a csv file using **stream API** throws an error as "list" argument must be an Array of Buffers
This error has occurred only with the latest csv-parse@5.0.1 package version.

**To Reproduce**
_Node version **14.16.1**
csv-parse version **5.0.1**_
Run the attached code for a csv file and would throw an error as "list" argument must be an Array of Buffers
```
const csvParser = require("csv-parse");
fs.createReadStream(filepath).pipe(csvParser.parse()).on('data', data => {
    console.log(data);
});
```

**Comment by hisayan** [comment]
is the version 6.0.1 ?

I encountered the same problem, now.
it woks fine on csv@5.5.3.

**Comment by wdavidw** [comment]
Version csv-parse@5.0.2 fixes the problem. Thank you for reporting.
