### ISSUE TITLE
Issue importing parse function with csv-parse@5.0.3

### ISSUE THREAD

**Issue by balihoo-gsuri** [adaltas/node-csv#304]
**Issue importing parse function**

`
import { parse as csvParse } from "csv-parse/lib/sync"
`
results in 
`'parse' can only be imported by using 'import parse = require("csv-parse/lib/sync")' or a default import.`

NodeJS Version 12.22
csv-parse version 5.0.3

what should be the import statement to fix this ?

**Comment by wdavidw** [comment]
According to the [docs](https://csv.js.org/parse/distributions/nodejs_esm/), if you are using ESM, which i guessed from your `import` statement, you shall use `import { parse } from 'csv-parse/sync';`

**Comment by moltar** [comment]
TypeScript imports aren't the same as ESM.

Our TypeScript project is still CJS.

**Comment by wdavidw** [comment]
Then refer to the [CJS doc](https://csv.js.org/parse/distributions/nodejs_cjs/). There is a demo project located in `demo/cjs`. The `./lib/parse_sync.ts` file inside of it contains `import { parse } from 'csv-parse/sync'` and I can execute it with Node.js `12.22.7` and the command `ts-node lib/parse_sync.ts`.

**Comment by balihoo-gsuri** [comment]
Thank you for the inputs. The initial error is resolved.
I am now able to import using 
`import { parse as csvParse } from "csv-parse/sync"`
