### ISSUE TITLE
unescaped quote char in middle of unquoted field throws error

### ISSUE THREAD

**Issue by mattpr** [adaltas/node-csv#305]
**Describe the bug**

Google Sheets frequently provides CSV where only some of the fields are quoted (`"`).
There are fields that are NOT quoted that include the quote character (`"`).  
That quoted character is NOT escaped (it is `"`, not `""`) because the field is not quoted.

Example:
```javascript
const { parse } = require('csv-parse');

var parser = parse({
  delimiter: '\t',
  quote: '"',
});
parser.on('error', function(err){
  console.error(err.message);
});
parser.write('40445\t<SCRIPT language="JavaScript1.1" SRC="https://ad.doubleclick.net...\t"more"\tfields');
```

> Pipeline failed CsvError: Invalid Opening Quote: a quote is found inside a field at line X
> node_modules/csv-parse/dist/cjs/index.cjs:761:19

I didn't find anything recent that is related.  Found [this](https://github.com/adaltas/node-csv/issues/46#issuecomment-8002712) from 2012.

> The current rule is as follow, if a field contains a quote charactere, then it must be surrounded by this quoted charactere.

Is this still the case?  

It seems to me that if the field isn't quoted (no quote char after the field delimiter) that quote escaping shouldn't be mandatory.

I can work around this by specifying `quote: ''`...but then some of the fields which are quoted do not have the quotes removed.

This is with `csv-parse` `5.0.3`.

I know a potential answer is that I should build the CSV differently, however this is with a CSV(tab-separated) download direct from google sheets...so it isn't just me.

**Comment by wdavidw** [comment]
Hi @mattpr, have you come across the [`relax_quote`](https://csv.js.org/parse/options/relax_quotes/) option?

**Comment by mattpr** [comment]
Thanks for pointing that option out.

I do see the csv [rfc](https://datatracker.ietf.org/doc/html/rfc4180#section-2) (point 5) says...

> 5.  Each field may or may not be enclosed in double quotes (however
>        some programs, such as Microsoft Excel, do not use double quotes
>        at all).  **If fields are not enclosed with double quotes, then**
>        **double quotes may not appear inside the fields.**

I don't understand why this is a necessary requirement because...

I've always thought of CSV quoting as being primarily (only?) necessary in cases where a field delimiter/separator is contained within a field (ie we don't want to treat it as a delimiter).  

@wdavidw If you have some insight into this (other cases), I'd be happy for a quick note to expand my knowledge in this area.

But I respect the fact that is a requirement from the RFC...so thanks again for pointing me to the `relax_quote` option.

**Comment by wdavidw** [comment]
I am just trying to be as pragmatic as possible, no particular insight to provide.

**Comment by mattpr** [comment]
No worries.  I was just wondering if there were specific edge-cases you had come across as a csv-lib developer that warranted "no quotes without quoting" being a requirement in the RFC.  

Sounds like "no", which is fine...maybe there aren't any...we aren't re-writing the spec here.  

Thanks again!

**Comment by nh2** [comment]
> Google Sheets frequently provides CSV where only some of the fields are quoted (`"`).
> There are fields that are NOT quoted that include the quote character (`"`).

@mattpr I cannot reproduce this behaviour with Google Sheets from 2024-03-18.

If I create a cell containing `c"d`, Google Sheets's CSV download creates a file containing

```
"c""d"
```

which is compliant with RFC 4180.

**Comment by mattpr** [comment]
@nh2 -- Here is a repro for you:

https://docs.google.com/spreadsheets/d/139tKyH5-Mz7T5Y4zPltDXp1Hr1HJyzVXBYfRuQN7eRM/edit#gid=0

Download as TSV (tab separated CSV)...

![image](https://github.com/adaltas/node-csv/assets/1196252/419d1bc0-2b9f-47ca-8d32-3731a5358e9a)

Observe the tab-separated CSV file generated by gsheets has fields with the following attributes:
- fields are not quoted (not surrounded by `"`)
- fields contain `"` character without escaping

```bash
% cat /tmp/node-csv\#305\ -\ Sheet1.tsv
column A	column B
<SCRIPT language="JavaScript1.1" SRC="https://ad.doubleclick.net...	<SCRIPT language="JavaScr ipt1.1" SRC="https://ad.doubleclick.net...%
```

Logically, escaping `"` probably isn't necessary if the field itself is not quoted with the same character...since there is no ambiguity.  But if that is what the RFC says, then perhaps this should rather be a bug for google sheets instead of `node-csv`.  Anyway, just confirming the issue with gsheet is still there.
