### ISSUE TITLE
Treat omitted columns as null

### ISSUE THREAD

**Issue by flisboac** [adaltas/node-csv#307]
**Summary**

I want to be able to differentiate between empty string and null.

`csv-parse` should return objects whose fields are filled with either the value or null, depending on whether the value for a column is completely omitted (i.e. no content whatsoever) or not.

**Motivation**

When preparing a CSV dump of a database, some table columns may be strings, and can accept empty strings. If said column is also `NOT NULL`, there's little one can do to try and differentiate between `null` and `""` just by looking at the CSV file.

Also, in some models, an empty string CAN be a valid value, and indicate something other than null (i.e. the absence of value).

As an example... If quotation is mandatory for any non-null field, it's possible to differentiate between the two. For example:

```csv
id,user_id,comment,title,body
"1","1",,"some article",""
```

This CSV could be generated with a `csv-stringify` configuration that includes `columns`, `header: true` and `quoted_string: true`, for example.

In this example, I know for a fact just by looking at the CSV file that the value for the column `comment` in the first data line is null, because it's omitted, and all fields are supposed to be quoted (even when empty). Whereas I know that all other columns are non-null, including the `body` column, which is just empty (but NOT null). It is incorrect to assume `comment` is just empty string in this case.

This improves the chances of inferring the correct value when processing the CSV (null check + auto-format check), and reduces the need to have domain knowledge (or the amount of knowledge you need to have; i.e. knowing the exact data type for each column).

_Please, don't focus too much on this example, specifically. This is just to illustrate that it is possible to differentiate between null and non-null (including possibly empty) values pretty easily at the CSV level. In an ideal world, such a scenario wouldn't happen. But the world is not ideal, and I have come across similar scenarios in the past._

**Alternative**

There's no alternative to what I'm suggesting, AFAICT, because it's something that can only be implemented at the parser level. Please correct me if I'm wrong.

**Draft**

Add a new `csv_parse` configuration `null_if_omitted: boolean`, for which the default is `false`. If `null_if_omitted: true`:

- Any column with **some** content will be considered to have some value. An empty quote (i.e. `""`) will yield an empty value (string).
- Any truly empty column (i.e. with no quotes or characters whatsoever, as in the second column of `,,`) will yield a null-ish value (either `undefined` or `null`; not sure about this specifically).

**Comment by wdavidw** [comment]
Could you add a minimalist example of what you expect, it will help the comprehension.

**Comment by flisboac** [comment]
@wdavidw I'm sorry, I meant to come back with an example the day after your message, but was taken away by other things, and then I eventually completely forgot to reply. :(

Follows an example on how to use:

```js
const assert = require('assert');
const parse = require('csv-parse/lib/sync');

// Just the header and one record
const records = parse(
    'id,user_id,comment,title,body\n"1",100,,"my article",""',
    {
        columns: true,
        null_if_omitted: true,
    },
);

const record = records[0];

assert(typeof record === 'object' && record);
assert(record.id === '1');
assert(record.title === "my article");

// Note here: `user_id` is expected to be '100',
// because that's the content of its unquoted cell.
assert(record.user_id === '100');
// Note here: `body` is expected to be just empty string,
// because it's quoted, but not empty
assert(record.body === "");

// Note here: `comment` is expected to be null
// because it has no content whatsoever (i.e.
// zero characters between record separators)
assert(record.comment === null);
```

I hope it helps clarify what I'm proposing.

**Comment by gregfenton** [comment]
As per the PR submitted above, @wdavidw's response is likely a much cleaner/better answer to this than creating a whole new feature.  See https://github.com/adaltas/node-csv/pull/392#issuecomment-1608952558.

I recommend this Issue be closed.
