### ISSUE TITLE
csv-parse CHANGELOG missing documentation of the `skip_lines` v. `skip_record` option rename

### ISSUE THREAD

**Issue by Dtphelan1** [adaltas/node-csv#310]
**Describe the bug**

The upgrade from v4.x.x to v5.x.x introduces several renamed options for the csv-parse tool - in particular the project renames `skip_lines_with_empty_values`  to `skip_records_with_empty_values` and `skip_lines_with_error` to `skip_records_with_error`. While this was a breaking change, it has yet to be captured in the form of a line item in the CHANGELOG. I've created a fork of the project that addresses this shortcoming, and my upcoming PR will reference this issue. 

**To Reproduce**

Refer [here](https://github.com/adaltas/node-csv/blob/master/packages/csv-parse/CHANGELOG.md#500-2021-11-15) for the current state of the CHANGELOG, and refer [here](https://github.com/adaltas/node-csv/compare/csv-parse@4.16.3...csv-parse@5.0.0#diff-4111483bb2eabf6b6abe2f4333f853fd06e3927e0fc5f9f8abb0b49bb3dd505f) for evidence of this rename taking place between these version updates.

**Additional context**

None, other than thanks for creating such a great library 😄

**Comment by wdavidw** [comment]
Also refer to the publication announcing the release on [Adaltas](https://www.adaltas.com/en/2021/11/15/csv-version-6/)
