### ISSUE TITLE
This expression is not callable.

### ISSUE THREAD

**Issue by Zyles** [adaltas/node-csv#312]
**Describe the bug**

Updated the package and now my script is getting an error:

```
This expression is not callable.
Type 'typeof import("M:/Projects/project/node_modules/csv-parse/lib/sync")' has no call signatures.

8     const records = csvParser(fileData, {
```

What happened?

**To Reproduce**

```
import * as fs from 'fs'
import * as csvParser from 'csv-parse/lib/sync'

export async function CSVFile2Object(filePath: string) {
  try {
    const fileData = fs.readFileSync(filePath)

    const records = csvParser(fileData, {
      columns: true,
      skip_empty_lines: true,
      delimiter: ';',
      trim: true,
    })

    return records
  } catch (error) {
    throw new Error(error)
  }
}
```
**Additional context**

```
"csv": "^6.0.4"

node v14.17.4

npm 8.2.0
```

**Comment by wdavidw** [comment]
Please refer to the documentation, `lib/sync` is no longer valid with this version.

**Comment by Zyles** [comment]
Yeah the docs doesn't work.

https://csv.js.org/parse/api/sync/

`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/sync' is not defined by "exports"`

**Comment by wdavidw** [comment]
I'll update the sentence "Import the csv-parse/lib/sync module to use it.", it is not up-to-date. Look at the sample:  `import { parse } from 'csv-parse/sync';`. Note, every sample is executed as part of the unit test suite to make sure they work.
