### ISSUE TITLE
csv-stringify: stringifier.stringify() suddenly returns a string

### ISSUE THREAD

**Issue by derhuerst** [adaltas/node-csv#315]
`csv-stringify@6.0.4` suddenly changed its return format from `string` to `[undefined, string]`.

```shell
node -v
# v17.0.1
npm init --yes
npm i csv-stringify@6.0.3
node -e 'const {Stringifier} = require("csv-stringify"); const s = new Stringifier({quoted: true}); console.log(s.stringify(["de:06438:3529:1:1", "1:object-object:50.1230:8.8290", "32"]))'
# "de:06438:3529:1:1","1:object-object:50.1230:8.8290","32"
npm i csv-stringify@6.0.4
node -e 'const {Stringifier} = require("csv-stringify"); const s = new Stringifier({quoted: true}); console.log(s.stringify(["de:06438:3529:1:1", "1:object-object:50.1230:8.8290", "32"]))'
# [
#   undefined,
#   '"de:06438:3529:1:1","1:object-object:50.1230:8.8290","32"'
# ]
```

**Comment by wdavidw** [comment]
The doc never mention using the Stringifier class, but the `stringify` function instead. Consider it a private API. Also, you will potentially experience a lot of other issues using this function, which is expected to run in the context of the Node.js stream API.

**Comment by derhuerst** [comment]
> The doc never mention using the Stringifier class, but the `stringify` function instead. Consider it a private API.

I assumed that it is part of the public API surface because it is exported by the module.

**Comment by derhuerst** [comment]
What is the preferred way to generate CSV, iteratively (as in step by step) but *not* asynchronously, with a header? Like this?

```js
const {stringify} = require('csv-stringify/sync')

process.stdout.write(stringify([
	['1st', 'row'],
], {
	quoted: true,
	columns: ['foo', 'bar'],
	header: true,
}))

process.stdout.write(stringify([
	['2nd', 'row'],
], {
	quoted: true,
}))
```

```csv
"foo","bar"
"1st","row"
"2nd","row"
```

**Comment by wdavidw** [comment]
It is exported for people to hack on it. This is basically what you are doing but going into the source code and not following any documentation. Not even the internal unit test cover this directly. Nothing wrong with it, but from there, you are on your own.

To answer your question, you want to interact iteratively, with an API which is meant to be run asynchronous (quite obvious from the source code and anywhere else), then your best bet is to look at how `csv-string/sync` is working internally, which you probably did since you find the best way to do it. But things might break (not every day, this is quite exceptional looking at the last 10 years of history).

**Comment by derhuerst** [comment]
A 71x slowdown when using `require("csv-string/sync").stringify()` (see my benchmark above) is not tolerable for my use case unfortunately.

What do you think about adding a "fast path" next to it that doesn't normalise the arguments every single time, as an opt-in API for better performance? Would you accept a PR?

**Comment by derhuerst** [comment]
> For performance, we clearly state to use the stream API which is supported. From the [API](https://csv.js.org/stringify/api/) page: "This is the recommended approach if you need a maximum of power.".

While it is slower than synchronous generation in extreme cases (as in "lots of short rows, just CSV generation, no significant other processing"), in [my use case](https://github.com/derhuerst/match-gtfs-rt-to-gtfs/blob/dff77d37dabc9ae6e059ff963852d7fc7a7cbf72/readme.md#usage) it is barely noticeable (2m57s async vs 2m51s synchronously). 👍

**Comment by wdavidw** [comment]
It is actually quite good, I would have expected worse results. Thank you for sharing.

**Comment by derhuerst** [comment]
Because someone might be interested: As of `csv-stringify@6`, I use the following implementation, so that I can expose a single [generator function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction) that outputs multiple concatenated CSVs:

```js
function* (files) {
	const csv = new Stringifier({quoted: true})

	for (const {path, formatRow} of order) {
		const {formatRow} = formatters[name]
		for await (const rawRow of await readCsv(task.file)) {
			const row = formatRow(rawRow)
			let csvRow = null
			csv.api.__transform(row, (_csvRow) => {
				csvRow = _csvRow
			})
			yield csvRow
		}
	}
}
```

**Comment by wdavidw** [comment]
Be warned, this is using undocumented and internal apis which will certainly break in the future.
