### ISSUE TITLE
"require not defined" error thrown by some web bundlers

### ISSUE THREAD

**Issue by richardeschloss** [adaltas/node-csv#318]
**Describe the bug**

This is more of a bug with the chose web bundler than the node-csv package, but it's still worth discussing since people may encounter it.  Several bundlers statically analyze the code and sometimes falsely throw errors, even on commented out code. Specifically, if I'm running a Nuxt 3.x / Vite / Rollup project (ESM mode), and I try to use [csv-parse/dist/esm/sync.js](https://github.com/adaltas/node-csv/blob/master/packages/csv-parse/dist/esm/sync.js), I encounter a "require not defined error" and the error is occurring on this line:

https://github.com/adaltas/node-csv/blob/bab8d89a6eb3bc073233e27b7af0a50284b1590f/packages/csv-parse/dist/esm/sync.js#L1979

The magic fix is to remove that line. The static analyzer doesn't know better that it's a commented out line and should be ignored. I.e., it thinks a require() statement is being used when it really isn't, and throws an error anyway. I guess in that sense, it's a linter.

A clear and concise description of what the bug is, the CSV package version you are using.

[latest stable version]

**To Reproduce**

[not really needed because this issue is more informative, a minor suggestion to remove the commented out line. Does that nodejs odditity still exist in Node 16+?]. 

Please provide us with a unit test, an example code or even pseudo-code. It could be written in JavaScript or CoffeeScript, but not in TypeScript unless the bug is related to TypeScript.

What's important is to **limit the data** to the minimum as well as to **strip down the number of options** to the relevant ones with an impact. Do not reference an external file.

**Additional context**

**Comment by wdavidw** [comment]
Line is generated by the bundler, not much we can do about it :(
