### ISSUE TITLE
Info header boolean is always false

### ISSUE THREAD

**Issue by pjeannet** [adaltas/node-csv#319]
**Describe the bug**

We are using both the info and columns options on the parser and then accessing the generated infos from a piped transformer. The [doc ](https://csv.js.org/parse/info/#record-information) suggest that the `header` boolean should be set to true when `columns` is also at true but we noticed that it is always equals to false.
Did we misunderstand something or is it a (minor) bug?

**To Reproduce**

```ts
const parser = parse({
      columns: true,
      info: true,
    });
const transformer = transform(({ record, info: { header } }) => {
	  console.log(header);
	  return record;
});
```

**Additional context**

**Comment by wdavidw** [comment]
Please provide a working example because I dont see what `transform` is doing here. To test the behavior of info, you can use this example:

```js
parse('a,b,c\n1,2,3\n4,5,6', {
  columns: true,
  info: true
}, (err, records) => {
  console.info(err, records)
});
```

**Comment by pjeannet** [comment]
Hello, sorry I just quickly copied part of our code but it was not fully functionnal. 
Your sample is perfect for what I wanted to show : columns is at true, so header should be true but as you can see below its false.
![image](https://user-images.githubusercontent.com/6052793/151377985-dc8ad37c-3b57-4c33-a8ed-9948e27de437.png)

**Comment by wdavidw** [comment]
Ok, the doc is not very clear about it. `header` indicates that the field is part of the header. It only applies when the `columns` option is active. Otherwise, there is no header, every line is a record. You can see it in action with the `cast` option:

```js
parse('a,b,c\n1,2,3\n4,5,6', {
  columns: true,
  info: true,
  cast: (value, context) => {
    console.log(context.header);
    if(context.header){
      return value.toUpperCase();
    }else{
      return parseInt(value)/10;
    }
  }
}, (err, records) => {
  console.info(err, records)
});
```
