### ISSUE TITLE
 while using parse for reading streams returns error parse

### ISSUE THREAD

**Issue by srinumadhavv** [adaltas/node-csv#324]
>>>fs.createReadStream('kepler_data.csv')
       .pipe(parse({
          comment: '#',
          columns: true,
        }))

.pipe(parse({
          ^

TypeError: parse is not a function
    at Object.<anonymous> (/Users/srinumadhavvysyaraju/Desktop/node_practise/project1/index.js:6:11)

**Comment by wdavidw** [comment]
Parse not being not a function means you didn't follow the documentation, check your version and read the docs.
