### ISSUE TITLE
Why is it so complex?

### ISSUE THREAD

**Issue by softmarshmallow** [adaltas/node-csv#335]
There is no clear documentation how to use this.

Simply making csv text data from js object is so damn hard!!

Am i missing something?

**Comment by wdavidw** [comment]
It is not complex, it just reflects that not everyone has the same use-case (streaming or not) and the diversity of the JS landscape (ESM or CJS for example). There is a lot of samples to choose from, and every code from the documentation is tested as well. If you want something simple, just use the [sync API](https://csv.js.org/parse/api/sync/).
