### ISSUE TITLE
`Buffer is not defined` error when using in browser

### ISSUE THREAD

**Issue by SuperCuber** [adaltas/node-csv#340]
**Describe the bug**
Using `"csv-stringify": "6.1.0"`, when I run the import immediately there is an exception thrown saying `Buffer is not defined`.

**To Reproduce**

```js
import { stringify } from "csv-stringify/sync"
stringify(myData) // doesn't have to run, just be used so it's not tree-shaked
```

**Additional context**
I'm using vite and want to run this in the browser (Firefox)
The error is originating from the line
```js
const bom_utf8 = Buffer.from([239, 187, 191]);
```
And indeed trying to type `Buffer` in console gives undefined variable.

---

I suspect I might be importing something wrong - I probably missed some kind of documentation. The [browser demo](https://github.com/adaltas/node-csv/blob/59cf7a4333c08020a029fa6922483f058bec04ab/demo/browser/esm/stringify_sync.html) is not very helpful because it is imported in a very strange way - I don't think I can apply it to the way an npm import works...

**Comment by keemor** [comment]
Did you try https://csv.js.org/stringify/distributions/browser_esm/ ?

```js
import {stringify} from 'csv-stringify/browser/esm';
// Or
import {stringify} from 'csv-stringify/browser/esm/sync';
```

Cheers,

**Comment by GermaVinsmoke** [comment]
Looks like `vite` is unable to find the package - `[plugin:vite:import-analysis] Missing "./dist/esm/sync" specifier in "csv-stringify" package`.
