### ISSUE TITLE
How to set some meta infos  in front of Headers

### ISSUE THREAD

**Issue by jiahao-si** [adaltas/node-csv#347]
**Summary**

I need to set  some meta infos in front of Headers. But  I have no idea on how to do it, even though I have read the docs.

<img width="822" alt="image" src="https://user-images.githubusercontent.com/7621226/175781377-2c031bf9-6e88-4c8f-a319-2d458c5b9c62.png">

**Comment by wdavidw** [comment]
This is not directly related with the parser. If you are using the stream api, you must write (or pipe without closing the csv writer stream) to the stream before using this library. See [this example](https://github.com/adaltas/node-csv/blob/master/demo/issues-esm/lib/347.js).
