### ISSUE TITLE
Keep get parse not a function

### ISSUE THREAD

**Issue by juniorperkins41** [adaltas/node-csv#351]
![code](https://user-images.githubusercontent.com/108557609/176979816-54607c3a-3cd7-46ce-85bd-5f4569455c78.png)

Keep getting parse undefined

Even after installing csv parse

How do I run this code

**Comment by wdavidw** [comment]
Following the [documentation](https://csv.js.org/parse/api/stream/), it is `const {parse} = require('csv-parse')`
