### ISSUE TITLE
Support new lines in quoted fields

### ISSUE THREAD

**Issue by bluejack** [adaltas/node-csv#355]
**Summary**

Correct me if I'm wrong, but it looks like new lines within quoted fields are not supported.

**Motivation**

This is an occasional edge case for data we receive, but it breaks the record.

**Alternative**

We could pre-process the file to eliminate such situations, but it requires significant csv parsing to do that correctly.

**Draft**

If a newline is encountered that would break the cell by raising a quote-not-ended errors, determine whether treating the new line as part of the cell would eliminate the error and generate the correct number of rows.

**Additional context**

**Comment by bluejack** [comment]
Looking at closed issues, it looks like this is supported. I am going to close this pending further research on my side.

**Comment by wdavidw** [comment]
Yes, it has supported for years and I don't recall any pending issue with it: https://github.com/adaltas/node-csv/blob/master/packages/csv-parse/test/option.quote.coffee#L100-L114
