### ISSUE TITLE
Rows count limit

### ISSUE THREAD

**Issue by dalisoft** [adaltas/node-csv#363]
**Summary**

Could be nice to see property in options like `rowsLimit: 20`

**Motivation**

When i need to get only 20 lines from 100K lines CSV file database

**Alternative**

I'm tried `parser.end().destroy();` inside `onRecord` for `csv-parse` but seems it's skips that case.

See below please

**Draft**

```js
const parser = parse({
    skipEmptyLines: true,
    autoParseDate: true,
    trim: true,
    relaxColumnCount: true,
    delimiter: [";", ","],
    recordDelimiter: ["\n", "\r"],
    onRecord(record, context) {
      if (
        typeof options?.sheetRows === "number" &&
        context.lines + 1 >= options?.sheetRows
      ) {
        console.log(context, { sheetRows: options?.sheetRows });

        inputStream.unpipe(parser).destroy();
        parser.end().destroy();
      }

      return record;
    }
  });
```

**Additional context**

**Comment by wdavidw** [comment]
Have you seen the [`to` option](https://csv.js.org/parse/options/to/) ? It seems appropriate to your request.

**Comment by dalisoft** [comment]
Hi @wdavidw. Thank you. I seen docs and seems the option can be aliased with `limit`, `rowsCount` or similar because i'm somehow did not find out about this option
