### ISSUE TITLE
normalize_columns

### ISSUE THREAD

**Issue by 1Map** [adaltas/node-csv#364]
This used to work, now it does not anymore and gives an error:

`stringifyPipe.normalize_columns is not a function or its return value is not iterable`

My code that used to work:

```
const csvStringify = require('csv-stringify')

const stringifyPipe = csvStringify.stringify({
	bom: (options.target && options.target.bom) ?? true,
	delimiter: (options.target && options.target.delimiter) ?? ',',
	quoted: (options.target && options.target.quoted) ?? true,
	quoted_empty: (options.target && options.target.quoted_empty) ?? true,
	quoted_string: (options.target && options.target.quoted_string) ?? '"'
})

const [sErr, sColumns] = stringifyPipe.normalize_columns(stringifyPipe.options.columns)

```

**Comment by wdavidw** [comment]
You were using a private and undocumented API. The description would deserve the old and new version of Node.js being used. Chances are that `normalize_columns` is now in [`lib/api/normalize_columns_array.js`](https://github.com/adaltas/node-csv/blob/256d398ae66b9eb10fd6886e7d6ef4c0d5fa9a96/packages/csv-parse/lib/api/normalize_columns_array.js).
