### ISSUE TITLE
Add a filename extension to `from './index'`

### ISSUE THREAD

**Issue by rauschma** [adaltas/node-csv#367]
**Describe the bug**

With some module resolutions, TypeScript complains about `csv-parse/dist/esm/sync.d.ts`:

```
Relative import paths need explicit file extensions in EcmaScript imports
when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './index.js'?
```

To fix this issue, change https://github.com/adaltas/node-csv/blob/master/packages/csv-parse/lib/sync.d.ts

```diff
- import { Options } from './index';
+ import { Options } from './index.js';

  ···

  export {
    CastingContext, CastingFunction, CastingDateFunction,
    ColumnOption, Options, Info, CsvErrorCode, CsvError
- } from './index';
+ } from './index.js';
```

**Comment by LinusU** [comment]
This was fixed in #368, released in:

- csv-generate@4.2.1
- csv-parse@5.3.2
- csv-stringify@6.2.1
- csv@6.2.2
- stream-transform@3.2.1
