### ISSUE TITLE
Async iterator loads entire file before allowing iteration

### ISSUE THREAD

**Issue by brianbegy** [adaltas/node-csv#374]
**Describe the bug**

I'm trying to download a large (500MB) file, parsing it, and doing something async like writing to a database or calling a webhook _without loading the whole file into memory_.

The docs suggest using an async iterator to accomplish this, but when I do that, my memory usage spikes as it loads the entire file before allowing me to iterate.

**To Reproduce**

Create a parsers, open a file stream and pipe it to the parser.  Try to async iterate, measuring memory usage before and after.

**Additional context**

What _is_ the recommended process for doing something like this?

**Comment by wdavidw** [comment]
You should pipe to the writer, for example using the [pipe sample](https://csv.js.org/parse/recipes/stream_pipe/) where you replace `process.stdout` with your own writable stream.

**Comment by wdavidw** [comment]
I you have another problem, then you should open a new issue. Closing the current issue.
