### ISSUE TITLE
Broken link in doc page

### ISSUE THREAD

**Issue by mgifford** [adaltas/node-csv#376]
Going here https://csv.js.org/transform/

In the last paragraph:

> **Additional help**
> For usage and examples, you may refer to [example page](https://csv.js.org/transform/examples/), [the "samples" folder](https://github.com/adaltas/node-csv/tree/master/packages/stream-transform/samples) and [the "test" folder](https://github.com/adaltas/node-csv/tree/master/packages/stream-transform/test).

This page doesn't exist
https://csv.js.org/transform/examples/

**Comment by wdavidw** [comment]
Thanks, the change is online.
