### ISSUE TITLE
CSV parsing and stringify do not produce equivalent items

### ISSUE THREAD

**Issue by blade2005** [adaltas/node-csv#378]
**Describe the bug**

Conversion of Objects to CSV and parsing of CSV doc to objects results in incorrect casting types

**To Reproduce**
```javascript
import { stringify } from "csv-stringify/sync";
import { parse } from "csv-parse/sync";
const a = [{id: 1, value: false}, {id: 2, value: true}];
const result = stringify(a, { header: true});
const parsed = parse(result, {
  columns: true,
  skip_empty_lines: true,
  cast: true
});
console.log(parsed) // [ { id: 1, value: '' }, { id: 2, value: 1 } ]
```
the expected output of the above should be the same as input. Maybe I missed a flag that would help

**Comment by wdavidw** [comment]
This is exepected:
- csv-parse doesn't know about the original input
- `cast` is not destructive and don't decide if an empty string is a string or a boolean, nor if 1 or any `true` value converted to a string by csv-stringify is a boolean

The solution is to provide your own cast implementation, see [this example](https://github.com/adaltas/node-csv/commit/559d71060f37b26014a74a8f22c7c4155c8dde8c#diff-738b0e2d9dc4fd135535cd0aa37ad95e8e9296d0a67a65bd90ddc777d7998ed6R10-R15):

```js
cast: (value, {header, column}) =>
  header ? value :
  column === 'id' ? parseInt(value) : // Cast inteter as number
  column === 'value' ? !!value :      // Cast value as boolean
  value                               // Don't cast additionnal fields
```

**Comment by blade2005** [comment]
I get it now. Thank you for the sample code too (and the commit) :D
