### ISSUE TITLE
Tests are NOT a good source of inspiration, examples, and supported features

### ISSUE THREAD

**Issue by has-n** [adaltas/node-csv#379]
The document suggests 
```Consider the [tests](https://github.com/adaltas/node-csv/blob/master/packages/csv-stringify/test/option.columns.coffee) as an exhaustive source of inspiration, examples and supported features```

a. the tests are in Coffee
b. they're tests

It's quite frustrating to have to parse tests to figure out the API. This is a powerful package but fills me with dread every time I have to use it.

**Comment by wdavidw** [comment]
Understood, but that is your opinion and I should the language that fit me best. Feel free to suggest changes to the document when something is not covered or easily discover and you feel the need to jump into the tests.
