### ISSUE TITLE
Example in README doesn't appear to do anything

### ISSUE THREAD

**Issue by dandv** [adaltas/node-csv#382]
Pardon the naive question, but where exactly does the [example in the csv-parse README](https://github.com/adaltas/node-csv/tree/master/packages/csv-parse#example) open any CSV file?

**Comment by wdavidw** [comment]
csv-parse does not read the file system, it parses CSV data coming as a stream or a string. You can look at the [async iterator recipe](https://csv.js.org/parse/recipes/async_iterator/) or the [pipe recipe (replacing `generate` with `fs.readFile`)](https://csv.js.org/parse/recipes/stream_pipe/) for inspiration. Note, the README can certainly be improved but that shall answer your question.
