### ISSUE TITLE
stringify `header` and `cast` options: "no overload matches this call"

### ISSUE THREAD

**Issue by theetrain** [adaltas/node-csv#391]
**Describe the bug**

csv-stringify@6.4.0

I'm using `stringify` to cast output values within a file stream, but I see a type warning:

>No overload matches this call.
>The last overload gave the following error.
>Argument of type `{ header: boolean; cast: { boolean: (value: boolean, ctx: CastingContext) => string | boolean; }; }` is not assignable to parameter of type `Input`.
>Object literal may only specify known properties, and `header` does not exist in type `any[]`.

My code runs fine. This warning gives the impression that `header` and `cast` are mutually exclusive. 

When I remove `header`, I see a different warning:

>No overload matches this call.
>The last overload gave the following error.
>Argument of type `{ cast: { boolean: (value: boolean, ctx: CastingContext) => string | boolean; }; }` is not assignable to parameter of type `Input`.
>Object literal may only specify known properties, and `cast` does not exist in type `any[]`.

**To Reproduce**

Here's my code:

```js
fs.createReadStream(inFile)
  // ...
  .pipe(stringify({
    header: isOutFileNew,
//  ^^^^^ warning
    cast: {
      boolean: (value, ctx) => {
        if (ctx.header) return value
        if (ctx.column === 'Removed' && value === false) {
          return '0'
        }
        return String(value)
      }
    }
  }))
```

**Additional context**

My guess is the overloaded functions aren't being determined in the correct oder, where `Input` is being inferred instead of `Options`:

https://github.com/adaltas/node-csv/blob/22f4017e01e41572ca8cb8d4b19321f9a9b34288/packages/csv-stringify/lib/index.d.ts#L120-L121

**Comment by wdavidw** [comment]
Thank you for reporting your issue. TS is not my thing, if anyone interested into fixing this issue, please reproduce first the warning in a test before fixing.

**Comment by wdavidw** [comment]
I reproduce your [issue](https://github.com/adaltas/node-csv/commit/256d398ae66b9eb10fd6886e7d6ef4c0d5fa9a96). It was related to an invalid return type, `if (ctx.header) return value` shall be `if (ctx.header) return String(value)`.
