### ISSUE TITLE
document: how to detect types? eg string vs number

### ISSUE THREAD

**Issue by dcsan** [adaltas/node-csv#394]
**Summary**

Apparently this feature works but is very hard to find in the docs.
Since it's so basic a requirement, can it be highlighted in the docs somehow?

> how to detect the right types? even just for basic stuff like string vs int?

**Motivation**

basic need

**Alternative**

writing your own parser or casting fns?

**Draft**

```js
await fs.promises.writeFile(`${os.tmpdir()}/input.csv`, [
  'a,b,c',
  '1,2,3'
].join('\n'));
```

should return  ` a: 1, ` etc. not `a: "1" `

**Additional context**

seems like such a basic feature of this lib, am I missing something?

I know dates and all kinds of edge cases but a simple option for at least basic types would be major

**Comment by dcsan** [comment]
note to future self! this combo seems to work:

```ts
  const records = parse(raw, {
    columns: true,
    trim: true,
    rtrim: true,
    cast: true,
    skip_empty_lines: true,
    auto_parse: true,
  });
```

**Comment by wdavidw** [comment]
`{trim: true}` is internally converted to `{rtrim: true, ltrim: true}`, you can remove it.

**Comment by wdavidw** [comment]
Please close the issue if you answered your question.

**Comment by wdavidw** [comment]
From all the option above, only "auto_parse" is relevant to detect type and it is already documented. The option was renamed a few years ago as ["cast"](https://csv.js.org/parse/options/cast/). Improvements to the documentation are always welcome. Please be more specific on how you wish to improve the documentation if you wish a validation.

**Comment by wdavidw** [comment]
Closing for now. Don't hesitate to pursue the discussion if necessary.

**Comment by clicktodev** [comment]
the documentation of cast say it can only be a function but the TS types say it accepts Boolean as well.
Docs:
```
The cast option works at the field-level to alter its value. It is possible to transform the field's value or change its type.

Type: function
Optional

```
actual types
`(property) cast?: boolean | CastingFunction | undefined`

**Comment by wdavidw** [comment]
Thank you, feel free to update the doc with a PR.
