### ISSUE TITLE
Relax / relax_quotes not working

### ISSUE THREAD

**Issue by ilvjan** [adaltas/node-csv#395]
Input row: 19" Customs OÜ;14488896;Osaühing;;;R;Registrisse kantud;15.05.2018;;Kivi tn 4;8151;Tartu linn,Tartu linn,Tartu maakond;51009;3059063;;Tartu maakond,Tartu linn,Tartu linn,Kivi tn 4;https://ariregister.rik.ee/est/company/14488896	

Using online tool https://csv.js.org/convert/ with the "relax" option checked gives the error: Invalid Opening Quote: a quote is found on field 0 at line 1, value is "19""

Using it in node.js with "relax_quotes: true" gives the error: Invalid Record Length: expect 17, got 6...

Version: 6.3.1

**Comment by wdavidw** [comment]
Please provide a minimalist example.

**Comment by wdavidw** [comment]
Closing since there was no answer to my request. Feel free to re-open with a minimalist example.
