### ISSUE TITLE
Support for Node 20.x

### ISSUE THREAD

**Issue by lgandras** [adaltas/node-csv#396]
Currently there's only support for node 18.x

**Comment by wdavidw** [comment]
I develop with node 20.x. When you write that there is no support for above 18.x, what do you refer to, github actions (I don't feel the need to test for every major Node.js versions but I will accept a pull request) or some documentation (I don't believe we mention the supported versions)?

**Comment by lgandras** [comment]
My problem was when trying to run https://www.npmjs.com/package/csv-parse. I don´t know what solution I applied, but for now this seems to be working for me. My largest issue was installing the package, more than docs. I remember trying to see the CI to check how tests are done against version, but I believe that's internal only.

**Comment by wdavidw** [comment]
Closing since it is now working and without any precise description of the problem.
