### ISSUE TITLE
YYYY-01-01 getting parsed as the previous year

### ISSUE THREAD

**Issue by DaveCole** [adaltas/node-csv#401]
I have a CSV file that has several dates in the format YYYY-MM-DD where MM is 01 and DD is 01 - for some reason, when parsed, the date gets rolled back one day December 31st of the prior year.  I'll add the contents of the CSV at the bottom.

It looks like the date is parsed as GMT and then is being rolled back 8 hours for PST (where I am) - is there a way to correct for this in the options?

**To Reproduce**

Parse using the following options:
```
parsedValue = parse(value, {
        cast: true,
        cast_date: true,
        trim: true,
        skip_empty_lines: true,
      })
```

**Additional context**

Here's the CSV:

```
DATE,CBR06059CAA647NCEN
2007-01-01,84148
2008-01-01,100671
2009-01-01,136395
2010-01-01,170556
2011-01-01,199096
2012-01-01,220083
2013-01-01,235126
2014-01-01,264116
2015-01-01,250302
2016-01-01,243338
2017-01-01,227098
2018-01-01,205074
2019-01-01,210502
2020-01-01,220405
```

Here's a screencap of a console.log of the contents prior to parsing and immediately after:
![parseerrror](https://github.com/adaltas/node-csv/assets/959631/ab45dfdb-8e6f-4d79-8784-4ba024cdad98)

**Comment by wdavidw** [comment]
The `cast_date` option is [implemented](https://github.com/adaltas/node-csv/blob/master/packages/csv-parse/lib/api/normalize_options.js#L52C1-L55C7) as such:

```js
options.cast_date = function(value){
  const date = Date.parse(value);
  return !isNaN(date) ? new Date(date) : value;
};
```

If you are unhappy about it, for example, if you must define a particular timezone not present in your input records, then define your custom function. For example:

```js
parse(value, {
  cast: true,
  cast_date: function(value){
    const date = Date.parse(value+'T00:00:00');
    return !isNaN(date) ? new Date(date) : value;
  },
  trim: true,
  skip_empty_lines: true,
});
```
