### ISSUE TITLE
Link to Pipe recipe in docs is broken. 

### ISSUE THREAD

**Issue by tohagan** [adaltas/node-csv#404]
**Describe the bug**

This doc page refers to a Pipe recipie but the link is broken.

- https://csv.js.org/parse/api/stream/

**To Reproduce**

1. Visit https://csv.js.org/parse/api/stream/ and scroll to the bottom paragraph "Using the pipe function"
2. Click the link to the Pipe example
3. 404 page appears

**Additional context**

Issue #348 refers to the pipe example but it's no longer at the URL mentioned by this issue.

**Comment by tohagan** [comment]
I suspect it should be linked to this page:

- https://csv.js.org/parse/examples/stream_pipe/

**Comment by wdavidw** [comment]
Thank you @tohagan. Funny, this issue is numbered 404.
