### ISSUE TITLE
User-defined value generation

### ISSUE THREAD

**Issue by itstueben** [adaltas/node-csv#417]
**How to generate user defined values**

I'dont find how to add user definded values to the generator. 
How can i add my own calue gerators some like faker.js?

Please help out.
Thx

**Comment by itstueben** [comment]
Thanks for the hint but it seems that is not support (anymore). I use the following code and get the message:
> TypeError [ERR_INVALID_ARG_TYPE]: The "buf" argument must be an instance of Buffer, TypedArray, or DataView. Received an instance of Array

```
 generate({
        columns: [() => 'mydata'],
        encoding: 'utf-8',
        objectMode: true,
        length: args.count,
      }).pipe(process.stdout);
```

**Comment by wdavidw** [comment]
Please reproduce and share a full sample with minimal code. I will enrich the tests and update the definition file accordingly.

**Comment by itstueben** [comment]
i have a mini sample repo [here](https://github.com/itstueben/csv-generate)

In the Typescript File the types are wrong. I hope this helps what is wrong with the types

**Comment by wdavidw** [comment]
Version 4.4.0 hopefully fixes your issue.
