### ISSUE TITLE
Support parsing of quote characters within quotes

### ISSUE THREAD

**Issue by cohlar** [adaltas/node-csv#421]
**Summary**

Support parsing of a string such as `"diy" basket\ ""`.
I apologize in advance if that's already supported - I have tried to play with `relaxQuotes`, `quote` and `escape` options, without success.

**Motivation**

I have a CSV file which looks like this, and am failing to parse it with `csv-parse`:
```csv
ASIN,Search Query,Search Query Score,Search Query Volume,Impressions: Total Count,Impressions: ASIN Count,Impressions: ASIN Share %,Clicks: Total Count,Clicks: Click Rate %,Clicks: ASIN Count,Clicks: ASIN Share %,Clicks: Price (Median),Clicks: ASIN Price (Median),Clicks: Same Day Shipping Speed,Clicks: 1D Shipping Speed,Clicks: 2D Shipping Speed,Cart Adds: Total Count,Cart Adds: Cart Add Rate %,Cart Adds: ASIN Count,Cart Adds: ASIN Share %,Cart Adds: Price (Median),Cart Adds: ASIN Price (Median),Cart Adds: Same Day Shipping Speed,Cart Adds: 1D Shipping Speed,Cart Adds: 2D Shipping Speed,Purchases: Total Count,Purchases: Purchase Rate %,Purchases: ASIN Count,Purchases: ASIN Share %,Purchases: Price (Median),Purchases: ASIN Price (Median),Purchases: Same Day Shipping Speed,Purchases: 1D Shipping Speed,Purchases: 2D Shipping Speed,Marketplace,Reporting Date
B08X4YRW2H,7" x 10",76,2,40,2,5.0,0,0.0,0,-,-,-,0,0,0,0,0.0,0,-,-,-,0,0,0,0,0.0,0,-,-,-,0,0,0,Netherlands,2024-01-20
B08X4YRW2H,"diy" basket\ "",77,7,123,1,0.81,0,0.0,0,-,-,-,0,0,0,0,0.0,0,-,-,-,0,0,0,0,0.0,0,-,-,-,0,0,0,Netherlands,2024-01-20
B08X4YRW2H,1 year old birthday dress for girl,78,2,40,1,2.5,0,0.0,0,-,-,-,0,0,0,0,0.0,0,-,-,-,0,0,0,0,0.0,0,-,-,-,0,0,0,Netherlands,2024-01-20
```

**Alternative**

At the moment, this is my work-around - I replace "inner" double quotes by single quotes:
```ts
parse(replaceCsvInnerQuotes(csvString, "'"), {
  columns: true,
  trim: true,
  relaxQuotes: true,
});

function replaceCsvInnerQuotes(csv: string, doubleQuoteReplacement: string): string {
  return csv.replace(/(?<=,").*?(?=",)/g, (match) => match.replace(/"/g, doubleQuoteReplacement));
}
```

The work-around could potentially keep double quotes in the parse file by replacing the "inner" double quotes with a unique string, and then replacing this unique string back by double quotes with the `cast()` option (personally my data means the same to me with double or single quotes).

**Additional context**

At the moment I get the following error when trying to parse without my workaround: `Invalid Closing Quote: found non trimable byte after quote at line 4520`.

Thanks for your help, and for this awesome library - I have tried to implement a very lightweight csv parser, came across quite a few challenges, and now really value all your library solves for!

**Comment by wdavidw** [comment]
There are 2 invalid issue with the `"diy" basket\ ""` field. The second quote (position 5) should be escaped (by default with a second `"`) and, the last quote being escaped with the default `escape` option, it is closed. For example, the following would work `"diy"" basket\ """` with the options provided in your sample.

I am not sure there is much to do beside disabling quoting by setting the `quote` option to `false`.
