### ISSUE TITLE
Browser Streaming Support

### ISSUE THREAD

**Issue by helloimalastair** [adaltas/node-csv#428]
**Summary**

Support for [`ReadableStream`](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream)s with `csv-parse/browser/esm` parse.

**Motivation**

While `csv-parse` *technically* supports Streaming in the `esm` build, it does so via assorted Node-only APIs(`stream`, `Buffer` etc.).

**Alternative**

*May* be fixable by polyfilling the missing APIs, though my app is size-sensitive, so I would like to avoid that if possible.

**Draft**

I would probably rewrite the package to only use runtime-agnostic APIs, then polyfill support for Node-APIs back in(as that appears to be easier).

The package could also be split entirely, sharing code for internal stuff that doesn't care about which runtime it is using.

**Comment by wdavidw** [comment]
There is an implementation for Web Stream (see the [implementation](https://github.com/adaltas/node-csv/blob/master/packages/csv-parse/lib/stream.js) and the supporting [unit test](https://github.com/adaltas/node-csv/blob/master/packages/csv-parse/test/api.web_stream.coffee) for example). With Node.js engine. Not documented for lack of time and demand. Side note, tests shows that it was much slower than Node.js stream a few years ago, maybe it has changed.

**Comment by helloimalastair** [comment]
Ok, looking at that, it appears to work, though still requires a fill for the `Buffer` API. Other than that, it's good. Thank you!
