### ISSUE TITLE
Open a password protected excel file

### ISSUE THREAD

**Issue by jhgeluk** [adaltas/node-csv#434]
**Summary**

I have an excel file that is password protected, I could create an "unprotected" excel file myself. But this is quite cumbersome to do every time. It would be nice if this library could do this.

**Alternative**

The package [xlsx-populate](https://www.npmjs.com/package/xlsx-populate) has this option. But I would much rather use this package.

**Draft**

It would be preferred if we can add a "password" option like this:

```
{
    password: "PasswordHere!"
}
```

To any of the functions that are used to read the csv/excel.

**Comment by wdavidw** [comment]
The parser doesn't know about the native Excel file format, only CSV. My guess is that supporting password protected file is out of this package scope unless I am mistaking?
