### ISSUE TITLE
Camel-Cased Options are not used

### ISSUE THREAD

**Issue by pujux** [adaltas/node-csv#438]
although types are specifying that there is `Options.skipRecordsWithError` (see below) https://github.com/adaltas/node-csv/blob/9cbae01bfedd58b7f2e1228ad2149c6adc1c4939/packages/csv-parse/lib/index.d.ts#L196

the option is never used, and supposedly any other option that is camel-cased (haven't checked yet)

https://github.com/adaltas/node-csv/blob/6aadcace1a9e77ea308159733391e42ad019c5cb/packages/csv-parse/lib/api/index.js#L681-L694

why is that?

**Comment by wdavidw** [comment]
Camel-cased options are aliases and are converted to snake cases.

**Comment by pujux** [comment]
I couldn't find where that happens, could you provide me with the part where this is done?

**Comment by wdavidw** [comment]
https://github.com/adaltas/node-csv/blob/master/packages/csv-parse/lib/api/normalize_options.js#L9-L11 in the case of the parser

**Comment by pujux** [comment]
awesome, thanks!
